### ISSUE TITLE
Error: unexpected keyword

### ISSUE THREAD

**Issue by ivandebono** [williamjameshandley/anesthetic#106]
**Describe the bug**
Anesthetic returns an error (TypeError: __init__() got an unexpected keyword argument 'weights') when I run the Pypolychord test (Pypolychord runs correctly):

...
Last dead point: [-6.03521300e-03  8.31415451e-03  3.92729305e-03 -4.99459568e-03
  1.45918578e-04  5.48273830e+00  5.52729031e+00]
 ____________________________________________________
|                                                    |
| ndead  =         3285                              |
| log(Z) =           -2.99019 +/-            0.18190 |
|____________________________________________________|
Traceback (most recent call last):
  File "run_pypolychord.py", line 63, in <module>
    fig, axes = samples.plot_2d(['p0','p1','p2','p3','r'])
  File "/pbs/home/i/idebono/.local/lib/python3.6/site-packages/anesthetic-1.3.2-py3.6.egg/anesthetic/samples.py", line 357, in plot_2d
  File "/pbs/home/i/idebono/.local/lib/python3.6/site-packages/anesthetic-1.3.2-py3.6.egg/anesthetic/samples.py", line 166, in plot
  File "/pbs/home/i/idebono/.local/lib/python3.6/site-packages/anesthetic-1.3.2-py3.6.egg/anesthetic/plot.py", line 327, in kde_plot_1d
TypeError: __init__() got an unexpected keyword argument 'weights'

**To Reproduce**
PolyChordLite]$ python run_pypolychord.py

**Comment by lukashergt** [comment]
I believe this might have to do with an outdated scipy. Which version of scipy are you running, @ivandebono?

**Comment by ivandebono** [comment]
Version 1.1.0.

**Comment by lukashergt** [comment]
Yes, anesthetic requires now minimum scipy version `1.2.0`. @williamjameshandley we should add this to anesthetic's requirements.

**Comment by lukashergt** [comment]
@ivandebono which version of matplotlib are you running?

**Comment by ivandebono** [comment]
Ah, you're fast. I updated to version 3.2.2 and now it works without a hitch.

**Comment by lukashergt** [comment]
Great! :)
