### ISSUE TITLE
prior_samples shortcut

### ISSUE THREAD

**Issue by williamjameshandley** [williamjameshandley/anesthetic#118]
In a similar vein to `NestedSamples.posterior_samples()`, there should be a shortcut for `NestedSamples.prior_samples()` (basically posterior_samples, but with beta=0). This would be a good PR for a newcomer to implement to understand how to contribute to anesthetic.

**Comment by lukashergt** [comment]
@williamjameshandley, you mean `NestedSamples.posterior_points()`, right?

**Comment by williamjameshandley** [comment]
Yes -- my error. So the new interface would be something like `samples.prior_points()`, which is basically an alias for `samples.posterior_points(0)`, which is arguably less cryptic for those not familiar with anesthetic.

There could also similarly be a `samples.prior()` which could be a synonym for `samples.set_beta(0)`, although in that case the name `prior()` is possibly not quite as clear/consistent.
