### ISSUE TITLE
Both `logL` and `logL_birth` need modifying for importance sampling.

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#128]
Hi @williamjameshandley,

the current version of `NestedSamples.importance_sample` only modifies `logL`, which I believe works for the cases of discarding samples at the prior (logL=-inf) or likelihood (logL=-1e30) level. However, for a more general importance sampling (e.g. adding a new likelihood) I believe both `logL` _and_ `logL_birth` would need to be modified, right? If so, then the current version does not fully work as intended, yet.

A few questions to verify whether I properly understand the way `logL_birth` is recorded:
* `logL_birth` is not listed with the parameter set that was used to calculate it, right?
* For every `logL_birth != -inf` there should be a `logL` (tracing back the thread) with `logL_birth == -inf` corresponding to the first sample in a thread?

Follow-up thoughts/questions:
* The setup with `logL` and `logL_birth` seems not ideal, in that likelihood values are recorded double, even though they should always be the same, i.e. changing one should change the other identically.
* Would it be better to have something like a live point `ID` and a birth point `ID_birth` with `logL_birth(ID)=logL(ID=ID_birth)`, i.e. `logL_birth` becomes a function of `logL` and `ID_birth`? That way modifying `logL` would automatically handle `logL_birth` as well... 
* Is this line of thought something that should already be considered at the PolyChord level?

These thoughts would mean a quite fundamental change to the handling of nested samples. The only way I see of tackling this issue in the current format would be to search for `logL==logL_birth` and use the parameter set from the corresponding index to update `logL_birth` alongside `logL`, but doing this check on floats and on values that are modified seems not ideal to me.

**Comment by andrewfowlie** [comment]
A few thoughts:

- If you were to change logL_birth to an some ID that labels the iteration at which it was born, better to also rename it to e.g. id_birth?
- but I think this requires some care. once you've overwritten the logLs, I'm not even sure the logL_births are that useful. Once you've overwritten the logLs, it's not really any longer a nested sampling run. 
- so possibly the best thing to do would be that the importance sampling returns an upcasted 'weighted samples' object rather than a nested samples object.

but this requires some care

**Comment by lukashergt** [comment]
> * If you were to change logL_birth to an some ID that labels the iteration at which it was born, better to also rename it to e.g. id_birth?

That is indeed what I was trying to say when I was suggesting `logL_birth(ID)=logL(ID=ID_birth)`, although that might be a confusing way to write it. What I mean to say is that `ID_birth` could be a new column in `NestedSamples` and `logL_birth` turned into a function depending on `ID_birth` returning the `logL` value of the matching `ID`.

> * but I think this requires some care. once you've overwritten the logLs, I'm not even sure the logL_births are that useful. Once you've overwritten the logLs, it's not really any longer a nested sampling run.

This is the main point I am trying to raise/discuss with this issue that you indeed can*not* just add likelihoods to `logL` while leaving `logL_birth` unchanged. For example just adding the likelihood values from a BAOs to the `logL` of a Planck nested sampling run is not sufficient. The likelihood values need to be added to the `logL_birth` as well, which is more difficult, though, since the `logL_birth` are not listed with the parameter set that created them.


> * so possibly the best thing to do would be that the importance sampling returns an upcasted 'weighted samples' object rather than a nested samples object.

Hmm, it seems I might have phrased this poorly. The idea/wish is definitely to get an importance reweighted nested samples object. In a similar way to what has been done to the Planck MCMC chains annotated with a suffix `_post`, e.g. `base_plikHM_TTTEEE_lowl_lowE_post_BAO` is a Planck MCMC chain run with LCDM and baseline likelihoods and then importance sampled in postprocessing with the BAO likelihood.

**Comment by andrewfowlie** [comment]
sure, I think I get you. sorry I did indeed misread your idea a bit about `logL_birth(ID)=logL(ID=ID_birth)` 

My main point was that even if you update the `logL_birth`s by recomputing the likelihood assoicated with the model parameters in same way as you did for the `logL`s, it's no longer the results of an actual, consistent nested sampling run. You could end uo with points with `logL < logL_birth`, for example. So is it still really a nested sampling run?

**Comment by williamjameshandley** [comment]
Hi @lukashergt and @andrewfowlie, sorry to join late.

I'm afraid I'm not following the premise of this discussion i.e. that logL_birth should be modified for the current reweighting scheme. I can countenance the idea that there might be future situations where one might want/need to modify logL_birth in an alternative setting, but I don't think it should be needed/valid for the current reweighting setup.

In general, there is nothing that requires logL_birth to be associated with a point. For 'standard' nested sampling algorithms it generally corresponds to the lowest likelihood value of the set of live points before the last one is deleted, but that is a design choice that need not be the case. You could imagine a diffusive approach where you wanted to make this bound slightly larger or smaller. In particular, the case of a prior reweighted run provides a clear example of where that contour is no longer associated with a point if you have discarded it.

My intuition behind this is that when reweighting, you are adjusting the loglikelihoods that you calculate for each point, but keeping the birth contours as before, and discarding points that would not have been generated by this run. That way you get a (relatively downsampled) new nested sampling run that could in theory have been generated by a sampler that was freed from the requirement that its loglikelihood contour must be attached to a point (and had some 'mysterious' mechanism for choosing birth contours).

@lukashergt, do you have an evidence that the current scheme is not working as intended (either empirical or theoretical would do)?

**Comment by lukashergt** [comment]
Sorry, I didn't mean to spread confusion. I probably should have split my initial post in half and only posted the first half at first. I primarily really only meant to check my understanding of how `logL_birth` works in the scope of PolyChord and Anesthetic. Since my intuition seems to have been wrong, any discussion from the second half of my initial post is actually moot.


> [...], but that is a design choice that need not be the case.

This is a subtlety I did not appreciate so far and the source of my incorrect assumptions. 


> @lukashergt, do you have an evidence that the current scheme is not working as intended (either empirical or theoretical would do)?

No, no evidence, but so far I only looked seriously into the special cases of `-inf` and `-1e30` and thinking about the issue I drew some wrong conclusions about how I expected the code should work. On the contrary, I stress tested a bit with mock examples and the current implementation indeed works. I'll close this issue.

**Comment by williamjameshandley** [comment]
No problem @lukashergt -- this kind of conversation is what github issues are for. I still think that there may yet be an alternative weighting setup which may require one to modify a logL_birth contour, just not for our current reweighting scheme. Feel free to add those examples to the test suite if it's not too much work.

**Comment by lukashergt** [comment]
>  Feel free to add those examples to the test suite if it's not too much work.

I tested things with PC runs and Gaussian mock likelihoods, i.e. this involves additional data and therefore isn't really suitable for testing, unless we say that we want to expand on our example data.

**Comment by andrewfowlie** [comment]
@williamjameshandley  won't for example the insertion indexes and the test of them be a bit meaningless for reweighted chains?

And  `L < L_birth` could be very common and not very meaningful, because after reweighting L and L_birth could even be of different dimension. Imagine I run a NS with a narrow Gaussian likelihood N(0, 1). I then reweight multiplicatiively by a broad Gaussian, N(0, 10000) . The reweighting is fine as the likelihood is basically flat, but will cause `L < L_birth`  almost everywhere!

**Comment by lukashergt** [comment]
In regards to your second point, the caveat that importance sampling only makes sense  

1) when the initial sample sufficiently encompasses the importance sampled likelihood and
2) when there are sufficient samples in the bulk region of the importance sampled likelihood 

is not specific to NS, but also (probably even more so) the case in MCMC sampling. So, yes, this is definitely something the user needs to be aware of, but it is not really something new when it comes to importance sampling in post-processing.

**Comment by andrewfowlie** [comment]
Right, that was a case where 1 and 2 were satisfied but it resulted in a NS run with always L < L_birth. To make it even simpler, let’s say I just reweight only the likelihoods and not the L_births by a constant multiplicative factor of epsilon <<<< 1.

**Comment by lukashergt** [comment]
I think you can view situations of `L < L_birth` more as a feature than a bug. It allows you to penalise samples at the likelihood level. If you exclude samples at the prior level that won't contribute to the Occam penalty, whereas excluding them at the likelihood level means a model predicted regions of parameter space that are excluded by the data which should factor into Occam's razor.

**Comment by andrewfowlie** [comment]
I think we’ve got our wires crossed :) I just mean that in actual NS runs, L < L_birth is impossible. The a point with likelihood L and birth likelihood L_birth was found by sampling from the prior subject to L > L_birth. L_birth is like L^\star at the point when the point was born

So there is an argument that reweighted NS runs are not really NS runs at all And the insertion indexes and test is n example of something this would spoil.

**Comment by williamjameshandley** [comment]
Hi both -- let me try to uncross these wires, as you are both correct, but @andrewfowlie  I think is missing a critical piece of (undocumented as yet, [though there are plans for this]) information.

The reweighting scheme implemented in #122 #124 and [incepted here](https://github.com/williamjameshandley/anesthetic/pull/120#issuecomment-676537096) has two stages. The first is to adjust the logL contours, and the second is to discard any points which do not fulfil L > L_birth, and then recompute nlive. This ensures that the final product of this reweighting is a (variable nlive) nested sampling run, with fewer live points than the original.

This justifies @lukashergt's comment about the limitations of importance sampling:

> In regards to your second point, the caveat that importance sampling only makes sense
> 
> 1. when the initial sample sufficiently encompasses the importance sampled likelihood and
> 2. when there are sufficient samples in the bulk region of the importance sampled likelihood
> 
> is not specific to NS, but also (probably even more so) the case in MCMC sampling. So, yes, this is definitely something the user needs to be aware of, but it is not really something new when it comes to importance sampling in post-processing.

which in this case manifest themselves very clearly by ending up having a very low nlive (or possibly early terminating) nested sampling run.

It also makes clearer @andrewfowlie's concern

> @williamjameshandley won't for example the insertion indexes and the test of them be a bit meaningless for reweighted chains?

so yes the [insertion index approach](https://arxiv.org/abs/2006.03371) #117  will not be valid, but only because these are variable nlive runs. Any extension to the approach which allows for varying nlive will enable insertion indices to be used on these.

**Comment by andrewfowlie** [comment]
Got it :) sorry for the confusion Lukas, sometimes I write a bit too quickly and unclearly

**Comment by lukashergt** [comment]
No worries, I wasn't very clear myself. Will's explanation in terms of variable nlive NS runs makes things much clearer.
