### ISSUE TITLE
KeyError when providing `types` only in first call to `plot_2d`

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#13]
The following bug is introduced through #10:

When using `plot_2d` twice subsequently (i.e. in the same figure), but only providing the argument `types` the first time with `types` including the keyword `'upper'`, then the second call to `plot_2d` the default for `types` will be assumed which does not include `'upper'` and thus we are getting a KeyError.

Example for two `NestedSamples` instaces `ns1` and `ns2`:
```python
fig, ax = ns1.plot_2d(['n_s', 'r'], types={'diagonal': 'kde', 'lower': 'kde', 'upper': 'scatter'})
ns2.plot_2d(axes=ax)
```

This throws the following KeyError:
```python
.virtualenvs/py27env/lib/python2.7/site-packages/anesthetic/samples.pyc in plot_2d(self, axes, *args, **kwargs)
    288                         ax_ = ax.twin
    289                     elif ax._upper:
--> 290                         plot_type = types['upper']
    291                         kwargs = upper_kwargs
    292                     else:

KeyError: 'upper'
```

`types` should be inherited from first to second call to `plot_2d` within the same figure. Maybe make it an attribute of the figure or axes? Or can it be somehow inferred from the existing axes?

Current workaround is to consistently use the same `types` in every call.

**Comment by williamjameshandley** [comment]
The question really is whether this is a feature or a bug. It can't be inferred from the existing axes (yet), and I can imagine a use case where users wanted to overlay different types (e.g. a histogram and kde of the same data). The question is whether the default should be the last set of types plotted. In which case, one could simply monkey-patch types to the axes object and check if it has such a variable when inferring defaults

**Comment by lukashergt** [comment]
It's a bug in the sense that it throws an error.

But I agree that there is a feature hidden in there, not sure, though, whether I understand you correctly. Overlaying a 1D kde with a 1D histogram is already possible. It fails when the pre-existing axes do not match up with `types`. Thus the feature we'd need is that the second call to `plot_2d` should "redraw" or ignore the axes to it's needs as specified by `types`?

**Comment by williamjameshandley** [comment]
I would go with ignoring it, rather than re-drawing, as I think that's more consistent with the workflow that we've set up. In theory, ignoring would just be an additional switch in the plot_2d loop. 

It would be good to apply this update to #15, rather than master (or wait for that to be merged in).

**Comment by lukashergt** [comment]
Actually, this is not solved after all, just got hidden because of a change to the defaults. We still have the following two problems:

---
# 1. 
* `types` in 2nd call to `plot_2d` asks for _fewer_ plots (out of `{'diagonal', 'lower', 'upper'}`) than 1st call.
* This will raise a KeyError because the axes seem to request both upper and lower plots but the 2nd call to `plot_2d` sets `types` to only diagonal.

### Example code:
```python
ns = NestedSamples(root="./tests/example_data/pc")
params = ['x0', 'x1', 'x2']
fig, axes = ns.plot_2d(params)
ns.plot_2d(axes, types={'diagonal': 'hist'});
```

### Output:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-52-4a660ca2665c> in <module>()
      3 
      4 fig, axes = ns.plot_2d(params)
----> 5 ns.plot_2d(axes, types={'diagonal': 'hist'});

/scratch/.virtualenvs/py27env/lib/python2.7/site-packages/anesthetic/samples.pyc in plot_2d(self, axes, *args, **kwargs)
    277                     pos = ax.position
    278                     ax_ = ax.twin if x == y else ax
--> 279                     self.plot(ax_, x, y, plot_type=types[pos], *args,
    280                               **local_kwargs[pos])
    281 

KeyError: 'upper'
```
![image](https://user-images.githubusercontent.com/18258042/61141187-e9871480-a4c4-11e9-9b97-0fab119f6aa7.png)

---
# 2.
* `types` in 2nd call to `plot_2d` asks for _more_ plots (out of `{'diagonal', 'lower', 'upper'}`) than 1st call.
* Even though the 2nd call to `plot_2d` requests all of diagonal, lower, and upper, only the diagonal plots are actually drawn. No error raised, though.

### Example code:
```python
ns = NestedSamples(root="./tests/example_data/pc")
params = ['x0', 'x1', 'x2']
fig, axes = ns.plot_2d(params, types={'diagonal': 'hist'})
ns.plot_2d(axes, types={'diagonal': 'kde', 'lower': 'kde', 'upper': 'scatter'});
```

### Output:
![image](https://user-images.githubusercontent.com/18258042/61141300-2b17bf80-a4c5-11e9-9bbf-d27f8b9e569d.png)

**Comment by williamjameshandley** [comment]
I think point 2 is a feature rather than a bug. You are asking to plot the samples on a given set of axes in the second call, so it should only plot on the axes that are available, rather than drawing additional ones -- drawing additional ones would be fraught with complications, and not consistent with matplotlib (e.g. what if you asked to place a parameter in between x1 and x2).

Point one is indeed a bug, but is easily fixed by adding ``if pos in types:`` above the ``self.plot`` command. 

Ideally we'd have a more thorough set of tests that loop over all possible ways that you could call two plots.

**Comment by lukashergt** [comment]
Yes, the `if pos in types` I already added in the new pull request, but I think it also requires a call to `else: ax.plot([], [])` afterwards unless we manage to incorporate that differently.
