### ISSUE TITLE
MCMCSamples.importance_sample is missing weight adjustment

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#133]
**Describe the bug**
`MCMCSamples.importance_sample` does not adjust the weights at all (just the logL) which leads to importance sampling doing nothing.

**To Reproduce**
```
chain = MCMCSamples(orig_chain)
chain.tex = orig_chain.tex

fig, axes = chain.plot_1d("Omega_m", label='Original', color='blue')

logL_new = scipy.stats.norm.logpdf(chain.Omega_m, loc=0.3, scale=0.01)
reweighted = chain.importance_sample(logL_new, action='add')

reweighted.plot_1d(axes, label='Reweighted', color='red', linestyle='dashed')

if np.all(reweighted.weights == chain.weights):
    print("Weights equal")


plt.legend()
plt.show()
```
See #132 [here](https://github.com/williamjameshandley/anesthetic/issues/132#issuecomment-757992829) for plots.

**Expected behavior**
The reweighted chain should have different weights, the posterior should look different

**Screenshots**
![Figure_1](https://user-images.githubusercontent.com/40799217/104195533-a63f9600-541a-11eb-8a95-5117160fa896.png)

**Additional context**
`anesthetic/samples.py`, line 345. There is no code to adjust the weights:
```
    def importance_sample(self, logL_new, action='add', inplace=False):
        """Perform importance re-weighting on the log-likelihood.

        Parameters
        ----------
        logL_new: np.array
            New log-likelihood values. Should have the same shape as `logL`.

        action: str, optional
            Can be any of {'add', 'replace', 'mask'}.
                * add: Add the new `logL_new` to the current `logL`.
                * replace: Replace the current `logL` with the new `logL_new`.
                * mask: treat `logL_new` as a boolean mask and only keep the
                        corresponding (True) samples.
            default: 'add'

        inplace: bool, optional
            Indicates whether to modify the existing array, or return a new
            frame with importance sampling applied.
            default: False

        Returns
        -------
        samples: MCMCSamples
            Importance re-weighted samples.
        """
        samples = self.copy()
        if action == 'add':
            samples.logL += logL_new
        elif action == 'replace':
            samples.logL = logL_new
        elif action == 'mask':
            samples = samples[logL_new]
        else:
            raise NotImplementedError("`action` needs to be one of "
                                      "{'add', 'replace', 'mask'}, but '%s' "
                                      "was requested." % action)

        return modify_inplace(self, samples, inplace)

```
PS: `modify_inplace` does also not affect weights
```
def modify_inplace(orig, new, inplace):
    """Conditionally modify object inplace or return."""
    if inplace:
        orig.__dict__ = copy.deepcopy(new.__dict__)
    else:
        return new 
```

**Comment by williamjameshandley** [comment]
I agree that the code at the moment does nothing to modify the weights in `MCMCSamples.importance_sample`, and given the usual understanding of importance sampling, it should definitely do so.

It should be a fairly minor change. In the case of `action=='add'`, it just amounts to adjusting the weights by an appropriate factor (`samples.weights += np.exp(logL_new-logL_new.max())` would do). It's almost the same for `action=='replace'`, but you need to do this with the difference `logL_new-samples.logL` rather than `logL_new`. I don't think anything needs to be done for `action=='mask'`.

@lukashergt, as `importance_sample` was your original commit, do you want to have a go at the PR? Alternatively @Stefan-Heimersheim could have a go if he fancies contributing to the project to gain some FOSS/CI/PR CV experience points.

**Comment by lukashergt** [comment]
I finally managed to resurrect python on my laptop, so could take a go at it, but happy to let @Stefan-Heimersheim have go, should you have started working on this already.

**Comment by Stefan-Heimersheim** [comment]
I'm a bit short on time right now so I'd be happy for you to go ahead @lukashergt, thanks!
