### ISSUE TITLE
Update project requirements

### ISSUE THREAD

**Issue by yallup** [williamjameshandley/anesthetic#134]
**Describe the bug**
Calls to `anesthetic.plot.scatter_plot_2d` error with messages along the lines of:

`
FAILED tests/test_samples.py::test_plot_2d_types - AttributeError: type object 'Line2D' has no attribute 'items'
`

When running tests with mpl 3.1.3 (meeting current requirement of mpl>=3.1.2)

**To Reproduce**
Run test suite with mpl=3.1.3

**Expected behavior**
Update requirements file. It looks like the cbook.normalize_kwargs function changed since matplotlib>=3.3.0, so this should be sufficient but I only checked with 3.3.3 (latest)

**Additional context**

**Comment by lukashergt** [comment]
Thanks for flagging this up, @yallup, this will be updated in #138.
