### ISSUE TITLE
contour edgecolor matching to facecolor

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#140]
I propose changing the default behaviour of the color handling of contours for `anesthetic 2.0.0`. So far the default was to have colored contour faces and black edges. I suggest using the same color for faces and edges (the edges will be a bit darker than the faces anyhow, since the face colors come from a linear colormap ranging from white to input color).

This is mostly a question of aesthetical preference. When there is only one contourplot it doesn't matter all that much. However, when there are multiple contours, then I find that the different edgecolors help discern the contours.

What are other peoples opinions?

**Comment by lukashergt** [comment]
### Two quick examples to show the difference:

* example with **black edges**

```python
mc0 = MCMCSamples(root="/Users/lukashergt/Documents/Projects/AnestheticPrj/anesthetic/tests/example_data/gd")
mc1 = mc0.importance_sample(scipy.stats.norm.logpdf(mc0.x3, loc=0.4, scale=0.1))
mc2 = mc0.importance_sample(scipy.stats.norm.logpdf(mc0.x3, loc=0.6, scale=0.1))

fig, axes = make_2d_axes(['x1', 'x2', 'x3'])
mc0.plot_2d(axes, alpha=0.8);
mc1.plot_2d(axes, alpha=0.8);
mc2.plot_2d(axes, alpha=0.8);
```

![with black edges](https://user-images.githubusercontent.com/18258042/105646432-d0239e80-5e97-11eb-8580-9cc41bd230bd.png)



* example with **edgecolor equal to facecolor**

```python
fig, axes = make_2d_axes(['x1', 'x2', 'x3'])
mc0.plot_2d(axes, alpha=0.8, ec='C0');
mc1.plot_2d(axes, alpha=0.8, ec='C1');
mc2.plot_2d(axes, alpha=0.8, ec='C2');
```
![with edgecolor equal to facecolor](https://user-images.githubusercontent.com/18258042/105646447-e16cab00-5e97-11eb-9628-ec334d35c29f.png)

**Comment by williamjameshandley** [comment]
Both look nice in my view, and I'm happy with either to be the default. The first version emphasises the location of the contours, but at the expense of some information since you are right that it becomes harder to distinguish which contour is which. I think given that the precise location of the contours is not necessarily something we want to emphasise, I lean slightly toward the default being the second, but would be interested to hear others opinions

**Comment by lukashergt** [comment]
One more point that my example doesn't highlight well is the case of slim or small contours. In those cases, black contour lines can become quite dominant making it hard to differentiate colors.

**Comment by williamjameshandley** [comment]
@htjb, given your recent PR #145, do you have any views? Otherwise I would recommend that @lukashergt you go ahead and make a PR for a change to the default behaviour

**Comment by htjb** [comment]
@williamjameshandley Thanks for asking, aesthetically I prefer the black contours but I think in terms of interpreting/distinguishing the contours when there are different posteriors plotted I would agree that the change to coloured edges would be good. 

It is also easier for a user to change the edgecolor back to black if they wished too then to discern that the plotted colours are 'C0', 'C1' and 'C2' and set each edgecolor appropriately.  The later requires a bit more understanding, admittedly not a lot but a bit, of how the code picks the colours for the posteriors.
