### ISSUE TITLE
Confidence regions for 1D posteriors

### ISSUE THREAD

**Issue by htjb** [williamjameshandley/anesthetic#142]
**Is your feature request related to a problem? Please describe.**

I would like to be able to plot shaded regions under a 1D posterior corresponding to 68% and 95% confidence intervals using anesthetic. See example graph attached below where I have just used np.random.normal to generate some gaussian distributed "samples".

**Describe the solution you'd like**

I have written a code that can do this and could submit this as a pull request. The code is in the form of a function that takes in an axis to plot onto and the samples to produce the 1D posterior. I think it would fit in to the "plots.py" code in anesthetic as it is similar to the function "fastkde_contour_plot_2d". It will need documenting, flake 8 testing ect. if this sounds good?

**Additional context**
![example_1d](https://user-images.githubusercontent.com/40355093/106736066-e60a2f80-660c-11eb-825b-20c47867d3ef.png)

**Comment by williamjameshandley** [comment]
Many thanks @htjb. It would be good to see some detail of your implementation before having a think about where is best to incorporate this. In an ideal world, it would be great if we could give this as an option for all of the density-based plots (e.g. the scipy and fastkde ones), and you are also welcome to add your own new one (Kalepy #131 also still needs to be added).

**Comment by htjb** [comment]
Hi @williamjameshandley, thanks for the response. It would definitely be possible for the function I have written to take in an axis, a set of x data points and a corresponding posterior from any KDE implementation (eg scipy, fastkde, kalepy or [KDEpy](https://kdepy.readthedocs.io/en/latest/) as I am using) as arguments and plot the filled regions. You could then call the function from inside fastkde_plot_1d and kde_plot_1d based on a kwarg.

I can adapt the function to do this (straight forward change) and provide a  working example code if this helps?

Since, depending on the form of the posterior, finding the points along the posterior that = [0.68, 0.95] can involve interpolating a non montonic function the method I have divides the posterior up around turning points and interpolates it in sections.

**Comment by williamjameshandley** [comment]
It would be good to see a minimal working example (feel free to submit a PR, where we can discuss the implementation there). There might be a faster way to achieve this without the interpolation in a manner that is more consistent with the 2d contour plotting techniques.

The relevant code to have a look at here are the `{fast,}kde_contour_plot_2d`, where the levels are first computed using `anesthetic.utils.iso_probability_contours{,_from_samples}`, and then plotted using a relatively straightforward masking/levelling scheme.
