### ISSUE TITLE
Correct use of insertion indexes and derived KS p-values?

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#146]
Hi @andrewfowlie and @williamjameshandley,

I'd really appreciate some help with the correct usage of the insertion indexes feature in anesthetic. Might be useful to keep these questions in mind for future updates to documentation and/or demos.

The related functions I could find are [`compute_insertion_indexes(death, birth)`](https://github.com/williamjameshandley/anesthetic/blob/2c002434c194782da161b1c1e41851bbc6ca8088/anesthetic/utils.py#L195-L216) and [`insertion_p_value(indexes, nlive, batch=0)`](https://github.com/williamjameshandley/anesthetic/blob/2c002434c194782da161b1c1e41851bbc6ca8088/anesthetic/utils.py#L404-L468) in `utils.py` and the `NestedSamples` method [`_compute_insertion_indexes`](https://github.com/williamjameshandley/anesthetic/blob/2c002434c194782da161b1c1e41851bbc6ca8088/anesthetic/samples.py#L751-L753).

1) Are there other relevant functions/methods that I haven't listed? 

2) Why is the `NestedSamples` method `_compute_insertion_indexes` private?

3) I'm a bit surprised to find a user function such as `insertion_p_value` in the `utils.py` module. Wouldn't it be better to have it in `samples.py`?

4) Is the following a correct usage example?
    ```python
    >>> ns = NestedSamples(root="tests/example_data/pc_250")
    >>> ns._compute_insertion_indexes()
    >>> print(insertion_p_value(indexes=ns['insertion'], nlive=250, batch=0))
    {'D': 0.00833333333333286, 'sample_size': 3000, 'p-value': 0.9852795286994365}
    ```

5) How does the `batch` kwarg work? I am getting crazy numbers when changing this to anything other than zero:
    ```python
    >>> print(insertion_p_value(indexes=ns['insertion'], nlive=250, batch=0.1))
    >>> print(insertion_p_value(indexes=ns['insertion'], nlive=250, batch=0.5))
    >>> print(insertion_p_value(indexes=ns['insertion'], nlive=250, batch=1))
    >>> print(insertion_p_value(indexes=ns['insertion'], nlive=250, batch=2))
    >>> print(insertion_p_value(indexes=ns['insertion'], nlive=250, batch=5))
    {'D': 0.928, 'sample_size': 25, 'p-value': 4.7845190327959665e-17, 'iterations': (2975, 3000), 'nbatches': 120, 'uncorrected p-value': 3.9870991939966386e-19}
    {'D': 0.6080000000000007, 'sample_size': 125, 'p-value': 3.511416922609774e-39, 'iterations': (0, 125), 'nbatches': 24, 'uncorrected p-value': 1.4630903844207393e-40}
    {'D': 0.3759999999999999, 'sample_size': 250, 'p-value': 4.795157814840787e-30, 'iterations': (2750, 3000), 'nbatches': 12, 'uncorrected p-value': 3.995964845700656e-31}
    {'D': 0.18799999999999967, 'sample_size': 500, 'p-value': 5.329070518200751e-15, 'iterations': (2500, 3000), 'nbatches': 6, 'uncorrected p-value': 8.939759331997087e-16}
    {'D': 0.18799999999999967, 'sample_size': 500, 'p-value': 2.6645352591003757e-15, 'iterations': (2500, 3750), 'nbatches': 3, 'uncorrected p-value': 8.939759331997087e-16}
    ```

**Comment by andrewfowlie** [comment]
Thanks for raising this. First, about the private method. I'm not sure. My first thought was that it was supposed to be called in the constructor. But we have a test that just calls the private method. So I don't think so. 

About the tiny p-values. I think this is an ordering issue. When you split the insertion indexes into batches, their order makes a difference. They should be in birth order, but in the obvious way to write your code (as in your example) they are in death order. In death order, you get some non-trivial effects where similar indexes end up next to each other. This has a big effect when you break the set of indexes into batches, as you can get batches of very similar indexes.

So this works:

```
order = np.argsort(ns.logL_birth.values)
print(insertion_p_value(indexes=ns['insertion'].values[order], nlive=250, batch=100))
```

The idea behind the batches is that departures from uniformity for brief periods during a long run could be hard to spot when looking at all the insertion indexes. So we first break the whole set of insertion indexes into batches of size nlive * batch. We then look at each batch individually. 

Of course, there is a correction for multiple tests problem here. But still it gets back some sensitivity.
