### ISSUE TITLE
Different shades colours appearing in panels of the same triangle plot

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#147]
**Describe the bug**
When plotting contours with `samples.plot_2d`, in some cases the colours have different shades of Blue, but I would expect all the 68% regions to have the same colour.

**To Reproduce**
I didn't figure out under what conditions this happens. It does when I use my data:
```
fig, ax = dynesty_results.plot_2d(paramNames, types={'lower':'kde'})
```
![screenshot_2021-03-09_12-16-19](https://user-images.githubusercontent.com/40799217/110469364-7686d480-80d1-11eb-8619-5c3d89dd9541.png)
The central panel is a darker blue which is confusing. It doesn't seem to occur with simple toy data though. Same with the new feature from #145:
```
fig, ax = dynesty_results.plot_2d(paramNames, types={'lower':'hist', 'diagonal':'filledfastkde'})
```
![screenshot_2021-03-09_12-16-10](https://user-images.githubusercontent.com/40799217/110469387-7e467900-80d1-11eb-9439-9299ead57abd.png)
Here the colours seem all over the place.

**Expected behavior**
All 68% contours should be the same dark blue, and all 95% contours the same light blue. Like in this toy model:
```
a = anesthetic.samples.MCMCSamples(np.random.normal(loc=0, scale=1, size=(10000, 5)))
a.plot_2d(range(5),types={'lower':'kde'})
```
![screenshot_2021-03-09_12-23-45](https://user-images.githubusercontent.com/40799217/110470068-4f7cd280-80d2-11eb-88b0-51c4bb22c47a.png)

**Additional context**
* Occurs in the current master version as well as the fork in #145.
* I am using a jupyter-notebook
* The runs are produced with `dynesty`
```
dynesty_sampler = dynesty.DynamicNestedSampler(loglikelihood, uniform_to_params, nDim)
dynesty_sampler.run_nested()
dynesty_to_anesthetic = lambda s: anesthetic.samples.NestedSamples(data=s['samples'], weights=np.exp(s['logwt']), logL=s['logl'], columns=paramNames, tex=texDict)
dynesty_results = dynesty_to_anesthetic(dynesty_sampler.results)
```

Edit: It does not seem to always occur with dynesty and jupyter-notebook either, this toy model produces results as expected:
```
import anesthetic
import dynesty
import scipy.stats as sst
import numpy as np
import matplotlib.pyplot as plt

toylike = lambda p: sst.multivariate_normal.logpdf(p, mean=[0,0,0,0,0])
u = lambda x:x
s = dynesty.NestedSampler(toylike, u, 5)
s.run_nested()
dynesty_to_anesthetic = lambda s: anesthetic.samples.NestedSamples(data=s['samples'], weights=np.exp(s['logwt']), logL=s['logl'])
r = dynesty_to_anesthetic(s.results)
r.plot_2d(range(4))
plt.show()
```

Do you have any idea where this comes from or how I can debug this?

**Comment by williamjameshandley** [comment]
This here is a feature rather than a bug. On the GitHub frontpage README.rst:

>3. Many KDE plotting tools have conventions that don't play well with uniformly distributed parameters, which presents a problem if you are trying to plot priors along with your posteriors. anesthetic has a sensible mechanism, by defining the contours by the amount of iso-probability mass they contain, but colouring the fill in relation to the probability density of the contour.

The idea is that the colour dependency on height encourages you to intepret the nearly flat contours as being less tapered. If the 2-sigma contours were coloured lighter regardless of the height of the contour, then they eye can interpret that region as being more excluded than it is.

**Comment by Stefan-Heimersheim** [comment]
Oh thanks for explaining this! I didn't realize that meant but now that you say it I see that this refers to this effect. So do I understand this correctly, the lines refer to the confidence limit as in

int_{-inf}^{lower line} posterior(x) = 0.16, int_{lower line}^{upper line} posterior(x) = 0.68

and the color refers to the average posterior/pdf in the region?

color = int_{lower line}^{upper line} posterior(x) dx / int_{lower line}^{upper line} 1 dx

I am not sure about the 2nd one / how exactly the color "in relation to the probability density" is defined
