### ISSUE TITLE
Including prior limits in 2D posterior plots

### ISSUE THREAD

**Issue by dominicanstey** [williamjameshandley/anesthetic#148]
I had a quick question about the functionality of anesthetic. I've been trying to work out how to set prior boundaries on the corner plots produce by the [plot_2d](
https://github.com/williamjameshandley/anesthetic/blob/633c076a92a8daec259fdb6cec76f758eb621e69/anesthetic/samples.py#L271-L344) method, in the manner of getdist's ranges. I've found that the 2d plotting functions have optional parameters for x and y max and min, but these these wouldn't take multiple values for the different parameters, so I assume I'm using them wrong. I couldn't find an example of this in the plot gallery, so I wanted to ask how I should go about doing this.

**Comment by Stefan-Heimersheim** [comment]
In my plots I am currently doing it manually, if this is helpful:
```python
    for i in range(len(paramNames)):
        for j in range(len(paramNames)):
            if i!=j:
                axes[paramNames[i]][paramNames[j]].set_xlim(prior_bounds[i])
                axes[paramNames[i]][paramNames[j]].set_ylim(prior_bounds[j])
```
If you have only a lower/upper plot change to `i<j` or `i>j` (not sure which way around), and you can handle diagonal plots if `i==j`.

**Comment by williamjameshandley** [comment]
Many thanks @Stefan-Heimersheim. This is indeed a clear approach.

As a minimum working example
```python

from anesthetic import NestedSamples

samples = NestedSamples(root='./tests/example_data/pc')

fig, axes = samples.plot_2d(['x0','x1','x2'])
```
![Figure_1](https://user-images.githubusercontent.com/3708486/111680619-52866a00-881a-11eb-9b2e-faa4bd77977b.png)


The following are equivalent pandas-like ways of adjusting a single set of limits

```python
axes.x0.x0.set_xlim(-0.2,0.2)
axes.loc['x0','x0'].set_xlim(-0.2,0.2)
axes.iloc[0,0].set_xlim(-0.2,0.2)

```
![Figure_1](https://user-images.githubusercontent.com/3708486/111680738-6d58de80-881a-11eb-83bb-f55a2bceb820.png)

Note that the shared axes means that adjusting one axis adjusts all the corresponding ones (this is particularly useful for zooming in or out of interactive plots).

This means that the pandas equivalent of @Stefan-Heimersheim  's like code is:
```python
xlims = [[0, 0.3], [-0.4, 0], [0, 0.5]]
ylims = [[0, 0.3], [-0.4, 0], [0, 0.5]]

for i, x in enumerate(axes.columns):
    for j, y in enumerate(axes.index):
        axes.loc[y,x].set_xlim(xlims[i])
        axes.loc[y,x].set_ylim(ylims[i])
```
![Figure_1](https://user-images.githubusercontent.com/3708486/111682272-0fc59180-881c-11eb-92a2-3fa56ce945f4.png)

but in practice this can be accomplished for a square plot by scanning across a single row
```python
for i, lim in enumerate(xlims):
    axes.iloc[0,i].set_xlim(lim)
```
