### ISSUE TITLE
fastkde plots change parameter limits

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#149]
**Describe the bug**
Using `fastkde` in `plot_2d` sometimes increases the plot limits, e.g. adding unwanted white borders around histograms. (I think this behavior might also influence 68% bounds on `b` from `facecolor=True` but I did not confirm this yet.)
![bug](https://user-images.githubusercontent.com/40799217/112223716-30c62200-8c22-11eb-8ed3-28c31254d85d.png)
Maybe this happens because FastKDE usually returns a few bounds beyond the given range and those might somehow get taken into account.

**To Reproduce**
```python
import matplotlib.pyplot as plt
import numpy as np
import anesthetic
a = np.random.uniform(size=(1000,2))
b = anesthetic.samples.MCMCSamples(a, columns=['a','b'], limits={'a':[0,1], 'b':[0,1]})
fig, ax = b.plot_2d(['a','b'], types={'lower':'hist', 'diagonal':'fastkde'})
plt.show()
```

**Expected behavior**
Limits [0,1] as given:
![expected](https://user-images.githubusercontent.com/40799217/112223688-299f1400-8c22-11eb-985e-290d3cfc2c56.png)

**Additional Context**
The author of #148 might have had the same problem, I only had to adjust prior limits due to this fastkde problem. Now however I also plot 68% limits in my plots and noticed they do not align with the ones I derived with scipy's `gaussian_kde` (`kde` in anesthetic), so while investigating that I found this.

**Comment by Stefan-Heimersheim** [comment]
A similar issue occurs when using `fastkde` in the lower triangle
```python
import matplotlib.pyplot as plt
import numpy as np
import anesthetic
a = np.random.uniform(size=(1000,2))
b = anesthetic.samples.MCMCSamples(a, columns=['a','b'], limits={'a':[0,1], 'b':[0,1]})
fig, ax = b.plot_2d(['a','b'], types={'lower':'hist', 'diagonal':'kde'})
b.plot_2d(ax, types={'lower':'fastkde'})
plt.show()
```

(which is what I originally did in my plots) and in that case it can be "fixed" by commenting out the two `ax.plot([], [])` lines in `samples.py` (`plot()`, line ~150). Not sure if that is related to the bug or if that just accidentally avoids it.

**Comment by lukashergt** [comment]
Hi Stefan,

thanks for raising this and for you MWE. It is quite a subtle difference which would be hidden most of the time. It becomes apparent only in the `'hist'`-`'fastkde'` combination.

Note for anyone that might stumble onto this: This is mostly an issue of desired default settings. You can always do an explicit call to `ax.iloc[1, 1].set_xlim(xmin, xmax)` to force your desired bounds.

## 1) 

#150 should fix the issue from your first post. Would be great if you could test the PR and confirm that this solves the issue.

&nbsp;

## 2)

> A similar issue occurs when using `fastkde` in the lower triangle

With regards to this issue from your second post, I believe there might be another subtle bug hidden there, where `'fastkde_contour_plot_2d'` works fine for lower triangle only plots, works fine in combination with specified 1d diagonal plots, but does not like to be applied to a lower+diagonal grid with only lower specified. To illustrate this, we can further reduce your example by dropping the first plot call and setting `'diagonal': None`:

```python
import matplotlib.pyplot as plt
import numpy as np
import anesthetic
a = np.random.uniform(size=(1000, 2))
b = anesthetic.samples.MCMCSamples(a, columns=['a', 'b'], limits={'a': [0, 1], 'b': [0, 1]})
fig, ax = b.plot_2d(['a', 'b'], types={'lower': 'fastkde', 'diagonal': None})
plt.show()
```

This means the issue has to do with the linking of 1d with 2d plots, which is a lot trickier to get right.

**Comment by lukashergt** [comment]
> (which is what I originally did in my work) and in that case it can be "fixed" by commenting out the two `ax.plot([], [])` lines in `samples.py` (`plot()`, line ~150). Not sure if that is related to the bug or if that just accidentally avoids it.

It is related to my smaller example from my previous post. Since you are passing `ax` to plot 2d, you are passing 3 axes instances, but you actually only intend to use one of them (the lower, not the diagonals). 

Hence, the correct way is actually to only pass the axes that you intend to use, i.e.:

```python
import matplotlib.pyplot as plt
import numpy as np
import anesthetic
a = np.random.uniform(size=(1000, 2))
b = anesthetic.samples.MCMCSamples(a, columns=['a', 'b'], limits={'a': [0, 1], 'b': [0, 1]})
fig, ax = b.plot_2d(['a', 'b'], types={'lower': 'hist', 'diagonal': 'kde'})
b.plot_2d(ax.iloc[1:, :1], types={'lower': 'fastkde'})
plt.show()
```
Instead of working with numerical indexing with `.iloc` you can also use `.loc` and pass the row and column labels (you could do this for various subsets of the triangle plot and you can even use the usual python slicing with a colon):
```python
b.plot_2d(ax.loc[['b'], ['a']], types={'lower': 'fastkde'})
```

&nbsp;
---
&nbsp;

With this in mind, do we see the issue as a bug or is it down to the user to pass the correct axes? Thoughts? Maybe @williamjameshandley would want to weigh in on this?

**Comment by Stefan-Heimersheim** [comment]
> Hence, the correct way is actually to only pass the axes that you intend to use, i.e.:

This is very helpful and interesting! Can you also tell me how to pass on diagonal axes?
I tried `b.plot_2d([ax.iloc[0,0], ax.iloc[1,1]], types={'diagonal':'fastkde'})` but that just produces another plot, and `ax.loc[['a', 'a'], ['b', 'b']]` fails as well.

I think it should be possible and desired to simplify this for the user, in particular since the behaviour is inconsistent at the moment. Here is another example:
```python
import matplotlib.pyplot as plt
import numpy as np
import anesthetic
a = np.random.uniform(size=(1000,2))
b = anesthetic.samples.MCMCSamples(a, columns=['a','b'], limits={'a':[0,1], 'b':[0,1]})
fig, ax = b.plot_2d(['a','b'], types={'lower':'hist', 'diagonal':'kde'})
b.plot_2d(ax, types={'diagonal':'fastkde'}, facecolor=True)
plt.show()
```
produces
![bug](https://user-images.githubusercontent.com/40799217/112297533-eb3f3e80-8c8d-11eb-9613-a7aa4d943716.png)
while the same with `facecolor=False` gives
![nobug](https://user-images.githubusercontent.com/40799217/112297595-fc884b00-8c8d-11eb-8e20-31f9927263c5.png)

**Comment by lukashergt** [comment]
> Can you also tell me how to pass on diagonal axes?

You can only take square subsets of pandas (i.e. subsets that can be described by row and column slices). To do all diagonals you'll need a for loop like this:

```python
for i in ax:
    b.plot_2d(ax.loc[[i], [i]], types={'diagonal': 'fastkde'})
```

That said, you are right that there seems to be an inconsistency when it comes to the use of 1d facecolor which was newly introduced recently. Note, though, that `facecolor=True` in diagonal plots doesn't make much sense for uniform distributions and for example for a normal distribution things work fine. Can you describe a bit more what you are trying to achieve?

**Comment by Stefan-Heimersheim** [comment]
Thanks a lot for your help @lukashergt. My plot works now but for the benefit of people with similar problems I should describe what I want to do and how it works now:

> Can you describe a bit more what you are trying to achieve?

I plot MCMC and NestedSampling results and my parameters are quite unconstrained, looking like [here](https://github.com/williamjameshandley/anesthetic/issues/147). What I want to do in a triangle plot is the following:
* In the lower triangle show histograms of the data, together with 68% confidence contours (kde, non-filled).
* In the diagonal plot show 1D posteriors (kde) and in some of them show 68% confidence contours.

I do this by first plotting non-filled contours for everything, then adding the filled contours for selected panels and finally adding histograms in the background. The tricky parts where
* When plotting the diagonals, pass single panels as @lukashergt suggested `ax.loc[['a3'],['a3']]`
* When plotting the histogram (lower-only), don't pass the diagonal elements. This is the function I used for this
```python
def lower_axis(ax):
    lower_ax = {}
    for key in ax.keys():
        lower_ax[key] = {}
        for key2 in ax[key].keys():
            if key != key2:
                lower_ax[key][key2] = ax[key][key2]
            else:
                lower_ax[key][key2] = None
    return pandas.DataFrame(lower_ax)
```

Here is a full example showing what I meant:
```python
import anesthetic
import matplotlib.pyplot as plt
import numpy as np
import pandas
import scipy.integrate as sin
import scipy.stats as sst

paramNames = ['a1','a2','a3','a4']
limits = {'a1':[0,1], 'a2':[0,1], 'a3':[0,1], 'a4':[0,1]}

np.random.seed(42)

#Generate mock data
a = np.random.uniform(size=(1000,4))
weights = 1-np.exp(-1/2*(a[:,2]**2+0.5*a[:,3]**2))
a_flat = []
for i in range(len(weights)):
    for j in range(int(weights[i]*100)):
        a_flat.append(a[i])
a_flat = np.array(a_flat)
np.random.shuffle(a_flat)

dynesty_results = anesthetic.samples.MCMCSamples(a_flat, columns=paramNames, limits=limits)

# Plot KDE contours

# [Probably another bug]: fastkde and levels=[0.68] not gives an error
fig, ax = dynesty_results.plot_2d(paramNames, types={'lower':'kde', 'diagonal':'kde'}, facecolor="None", diagonal_kwargs={"color":'orange'}, lower_kwargs={"levels":[0.68], "color":'black'})
dynesty_results.plot_2d(ax.loc[['a3'],['a3']], types={'diagonal':'kde'}, diagonal_kwargs={"facecolor": True}, levels=[0.68], color='orange')
dynesty_results.plot_2d(ax.loc[['a4'],['a4']], types={'diagonal':'kde'}, diagonal_kwargs={"facecolor": True}, levels=[0.68], color='orange')

# Plot manual 68% lines to double check

# [Maybe another bug]: 68% lines don't line up

k1 = sst.gaussian_kde(dynesty_results['a3'])
k2 = sst.gaussian_kde(dynesty_results['a4'])
N=10000
K1 = k1(np.linspace(0,1,N))
K2 = k2(np.linspace(0,1,N))
K1_68 = np.linspace(0,1,N)[np.where(np.cumsum(K1/np.sum(K1))>0.32)[0][0]]
K2_68 = np.linspace(0,1,N)[np.where(np.cumsum(K2/np.sum(K2))>0.32)[0][0]]

ax['a3']['a3'].axvline(K1_68, color='red')
ax['a4']['a4'].axvline(K2_68, color='red')
ax['a3']['a4'].plot([0,K1_68],[K2_68,K2_68], color="red", linestyle='dashed')
ax['a3']['a4'].plot([K1_68,K1_68],[K2_68,0], color="red", linestyle='dashed')


def lower_axis(ax):
    lower_ax = {}
    for key in ax.keys():
        lower_ax[key] = {}
        for key2 in ax[key].keys():
            if key != key2:
                lower_ax[key][key2] = ax[key][key2]
            else:
                lower_ax[key][key2] = None
    return pandas.DataFrame(lower_ax)

# Larger mock data (my emcee sample) in the background.

# [Maybe another bug]: In some cases fastkde seems to produce nonsense contours even
# if I just have the same likelihood with more data (not in this example). [But that's why
# I use the histograms.] Will make a bug report when I get more time.
a = np.random.uniform(size=(10000,4))
weights = 1-np.exp(-1/2*(a[:,2]**2+0.5*a[:,3]**2))
a_flat = []
for i in range(len(weights)):
    for j in range(int(weights[i]*100)):
        a_flat.append(a[i])
a_flat = np.array(a_flat)
np.random.shuffle(a_flat)

emcee_results = anesthetic.samples.MCMCSamples(a_flat, columns=paramNames, limits=limits)

lower_ax = lower_axis(ax)
emcee_results.plot_2d(lower_ax, types={'lower':'hist'}, zorder=-10, color='orange')
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/40799217/112493162-d213bc00-8d79-11eb-8e6d-bdc491733ca0.png)

PS: @lukashergt's loop suggestion also solves the `facecolor=True` example from above, using
```python
for i in ['a','b']:
    b.plot_2d(ax[i][i], types={'diagonal':'fastkde'}, facecolor=True)
```
