### ISSUE TITLE
2D fastkde fails when len(levels) != 2 [contains workaround for len(levels)==1]

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#151]
**Describe the bug**
`plot_2d` with type `fastkde` fails with more or less than 2 `levels`, e.g.
```python
fig, ax = dynesty_results.plot_2d(paramNames, types={'lower':'fastkde'}, levels=[0.68])
fig, ax = dynesty_results.plot_2d(paramNames, types={'lower':'fastkde'}, levels=[0.68, 0.95, 0.975])
```
fail due to two contours being assumed in `utils.py`:
```python
    c0, c1, c2 = contours
ValueError: too many values to unpack (expected 3)
```
and
```python
ValueError: not enough values to unpack (expected 3, got 2)
```
respectively.

**To Reproduce**
MWE:
```python
import anesthetic
import matplotlib.pyplot as plt
import numpy as np

paramNames = ['a1','a2','a3','a4']
limits = {'a1':[0,1], 'a2':[0,1], 'a3':[0,1], 'a4':[0,1]}

np.random.seed(42)
a = np.random.normal(size=(1000,4), scale=0.1)
weights = 1-np.exp(-1/2*(a[:,2]**2+0.5*a[:,3]**2))

dynesty_results = anesthetic.samples.MCMCSamples(a, weights=weights, columns=paramNames, limits=limits)

fig, ax = dynesty_results.plot_2d(paramNames, types={'lower':'fastkde'}, levels=[0.68, 0.95, 0.975])
plt.show()
```

**Expected behavior**
Plot should work and show 1 or 3 contours. (It does work with `kde`.)

**Partial workaround**
If one contour (e.g. 68% only) is desired, `levels=[0.68, 0.68]` produces the desired result (even with matching line styles)
```python
fig, ax = dynesty_results.plot_2d(paramNames, types={'lower':'fastkde'}, levels=[0.68, 0.68], linestyle='dashed', linewidth=4)
```
![Figure_1](https://user-images.githubusercontent.com/40799217/112496841-fae98080-8d7c-11eb-887e-331924c25210.png)

**Additional context**
I think this is not an urgent bug as usually one wants only one or two contours (then the workaround works), or one can use the `kde` type in many cases.

**Comment by williamjameshandley** [comment]
@lukashergt it looks like this was introduced in #114. What do you think the best way to resolve this is?

**Comment by lukashergt** [comment]
@williamjameshandley I don't think this was introduced in #114. This has to do with line 683 in `plot.py`:

```python
    contours = iso_probability_contours_from_samples(p, weights=w)
```

The function `iso_probability_contours_from_samples` in principle takes the kwarg `contours`, which isn't passed though. If I remember correctly more than 2 contours was put on the TODO list, but turned out to be more complicated than anticipated and never got fully implemented... Am I remembering this wrong?

**Comment by lukashergt** [comment]
This issue is actually linked to #69. Since that is still an open issue, I don't think we ever got around to implement more than 2-sigma contours...
