### ISSUE TITLE
plot_1d_hist is not tested

### ISSUE THREAD

**Issue by williamjameshandley** [williamjameshandley/anesthetic#16]
Currently we have no tests that hit the ``plot_1d_hist`` function. In #15 I found that when trying a naive test on the travis and circle servers they were failing due to a keyword error that arose when astropy was not installed. It would be good to add some explicit tests of the ``plot_1d_hist``s for these purposes.

**Comment by lukashergt** [comment]
Do you want this to be added to #15? Or should I start a new PR for this?

**Comment by williamjameshandley** [comment]
Resolved by #15
