### ISSUE TITLE
log(likelihood) value from anesthetic does not match getdist

### ISSUE THREAD

**Issue by agnesemenaite** [williamjameshandley/anesthetic#171]
When I try loading the same chains using getdist and anesthetic, the samples.loglikes value from getdist is twice as large as MCMCSamples.logL value from anesthetic. It seems that anesthetic expects getdist to have 2xloglikelihood value, as is also seen in the anesthetic function to_getdist, where the new loglike is -2xlogL of anesthetic samples.

@cmbant has confirmed that getdist loglikes should be the likelihood value rather than chi2, so I am not entirely sure why the likelihoods differ. 

I exchanged emails with @williamjameshandley and he suggested there may have been some backward incompatible change in the relevant column for getdist and that @JesusTorrado might be able to help as well?

**Comment by JesusTorrado** [comment]
Hi @agnesemenaite 

Just to clarify: were the original chains created with Cobaya?

**Comment by agnesemenaite** [comment]
Hi @JesusTorrado, I tested this with chains created with Cobaya and CosmoMC and get the same behaviour for both

**Comment by cmbant** [comment]
FYI, in a recent getdist update I did fix a bug that was putting in a spurious factor of two when reading in from cobaya format chains

**Comment by lukashergt** [comment]
Hi @agnesemenaite, I've mostly worked on PolyChord output, but I did fairly recently create the PR #167 from my local branch, which might be useful if you are working with Cobaya MCMC output. Feedback would be most welcome.

**Comment by agnesemenaite** [comment]
> Hi @agnesemenaite, I've mostly worked on PolyChord output, but I did fairly recently create the PR #167 from my local branch, which might be useful if you are working with Cobaya MCMC output. Feedback would be most welcome.

Thanks, I am currently mostly using getdist chains, but will keep this in mind for future reference!

**Comment by agnesemenaite** [comment]
I updated my getdist but nothing seems to have changed, so I don't think that was part of the issue...

Also, I do not know if this is helpful but I came across this issue when I wanted to compare the usual way to compute suspiciousness from Bayes factor and information ratio with the MCMC shortcut from recent KiDS analysis using expectation values of log-likelihood. It is based on the fact that the sum of Kullback-Leibler divergence and log(evidence) give expectation value of logL. 

If I load nested sampling chains with getdist, the <logL> I get from there is roughly twice D+log.Z given by anesthetic...

**Comment by lukashergt** [comment]
My suspicion is that anesthetic didn't catch up to the GetDist changes Antony mentioned. Would be good for @williamjameshandley to weigh in on this.

#172 should fix this. @agnesemenaite Could you give that branch a try and report back?

**Comment by agnesemenaite** [comment]
> My suspicion is that anesthetic didn't catch up to the GetDist changes Antony mentioned. Would be good for @williamjameshandley to weigh in on this.
> 
> #172 should fix this. @agnesemenaite Could you give that branch a try and report back?

Cobaya samples now have the same log likelihood values on getdist and anesthetic

However, the following differences remain:
- for cosmomc samples:  log(likelihoods) getdist vs anesthetic
- for nested samples from cosmosis:  D+log.Z  from anesthetic vs < logL > from getdist

In both of these cases getdist value is twice as large

**Comment by lukashergt** [comment]
Hi @agnesemenaite, just to follow up on this, anesthetic should now (as of PR #172) correctly read CosmoMC samples, matching GetDist also for `logL`.

Regarding (raw) PolyChord output: You need to watch out that the _raw_ PolyChord `.txt` files have `-2*logL` in the second column. GetDist on the other hand assumes the second column in the `.txt` files to be `-logL`. Hence, I am not sure whether GetDist correctly reads data that was not generated by CosmoMC or Cobaya. I think you can't pass _raw_ PolyChord data to GetDist if the absolute `logL` values are relevant to you.

For that reason Cobaya separates:
* its own output `root_folder/fileroot` 
  (e.g. `root_folder/fileroot.1.txt` has `minuslogpost` or `-logL` in the second column) 
* from the raw PolyChord output `root_folder/fileroot_polychord_raw/fileroot` 
  (e.g. `root_folder/fileroot_polychord_raw/fileroot.txt` has `-2*logL` in the second column).

Unfortunately I am unfamiliar with the Cosmosis output.

**Comment by agnesemenaite** [comment]
Hi @lukashergt, that makes sense, thanks a lot!
