### ISSUE TITLE
Storing anesthetic samples to file does work only for some formats (HDF works, CSV and feather not)

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#176]
**Describe the bug**
Storing anesthetic `NestedSamples` in files only works sometimes. As I think that at least one method seems to work consistently it would be the simplest to just clarify this in the documentation.

**To Reproduce**
MWE, using anesthetic test data sets

```python
import pandas as pd
import anesthetic

# HDF
ns = anesthetic.NestedSamples(root='./tests/example_data/pc')
print(ns.logZ())
ns.to_hdf("ns.hdf", "nonsense")
ns2=anesthetic.NestedSamples(pd.read_hdf("ns.hdf"))
print(ns2.logZ())

# CSV
ns = anesthetic.NestedSamples(root='./tests/example_data/pc')
print(ns.logZ())
ns.to_csv("ns.csv")
ns2=anesthetic.NestedSamples(anesthetic.weighted_pandas.DataFrame(pd.read_csv("ns.csv")))
#ns2.drop(labels=['#'], axis='columns', inplace=True)
print(ns2.logZ())

# feather
ns = anesthetic.NestedSamples(root='./tests/example_data/pc')
print(ns.logZ())
ns.reset_index().to_feather("ns.feather")
ns2=anesthetic.NestedSamples(anesthetic.weighted_pandas.DataFrame(pd.read_feather("ns.feather")))
#ns2.drop(labels=['#'], axis='columns', inplace=True)
print(ns2.logZ())
```

Computing `logZ()` from the loaded CSV and feather samples returns:
```python
ValueError: cannot join with no overlapping index names
```
Looking at the loaded `ns2` object, it seems that it is not loaded as weighted sample:
```
>>> ns2
         #        weights        x0        x1  ...        x4        logL  logL_birth  nlive
0        0   0.000000e+00  0.839566 -0.927932  ...  3.904285 -777.011546        -inf    125
1        1  1.088407e-308  0.711607 -0.976572  ...  2.343259 -712.872399        -inf    125
```
It also has an additional index column `'#'` but that can be deleted and does not solve the problem.

**Expected behavior**
The loaded object behaves just like a `NestedSamples` object, including computing the evidence.
```
>>> ns2
                          x0        x1        x2  ...        logL  logL_birth  nlive
#    weights                                      ...                               
0    0.000000e+00   0.839566 -0.927932  0.174772  ... -777.011546        -inf    125
1    1.088407e-308  0.711607 -0.976572  0.359978  ... -712.872399        -inf    125
```

**Additional context**
Using up to date `master` branch code. I initially thought no saving worked but when I mentioned it on occasion, Will suggested that it _should_ work, so I checked again and found that indeed, it works using the HDF format. So I am happy with this but thought writing this up here might be helpful.

**Comment by lukashergt** [comment]
Not sure whether this was resolved Cambridge-internally, but since there is no record I just wanted to leave a few tips here.

Setup:
```python
import anesthetic
import pandas
ns = anesthetic.NestedSamples(root="./tests/example_data/pc")
```

## reading with CSV

You need to specify the index columns when reading:
```python
ns.to_csv("ns.csv")
ns2 = anesthetic.NestedSamples(pandas.read_csv("ns.csv", index_col=(0, 1)))
```

## reading with Feather

Feather is meant to be light weight and fast, but therefore does not work great with pandas' multi-indexing.

You can make things work by passing things more directly:
```python
ns.reset_index().to_feather("ns.feather")
data = pandas.read_feather("ns.feather")
data.drop(['#', 'weights', 'nlive'], axis=1, inplace=True)
ns2 = anesthetic.NestedSamples(logL=data.pop('logL'), logL_birth=data.pop('logL_birth'), data=data)
```


---


Would it be worth streamlining this a bit better? 

`WeightedSeries` and `WeightedDataFrame` might be the right place...?

And/Or expand our `read` folder with an `anestheticreader.py` that handles CSV or Feather files that were created by writing a `NestedSamples` object?
