### ISSUE TITLE
merge_samples_weighted does not reset_index which breaks sample compression

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [williamjameshandley/anesthetic#189]
**Describe the bug**
`merge_samples_weighted` 2 data sets with N samples each produces indices `0,1,2,...,N,0,1,2,...N` rather than `0,1,2,...,2N`.

**To Reproduce**
```python
import anesthetic
import numpy as np

prior_samples = []
for i in range(51):
	d = {"x": np.random.uniform(size=1000),
	     "y": np.random.uniform(size=1000)}
	tmp = anesthetic.MCMCSamples(d)
	prior_samples.append(tmp)

merge_prior = anesthetic.samples.merge_samples_weighted(prior_samples, weights=np.ones(51))
merge_prior.plot_2d(["x", "y"])
```
gives `IndexError: index 5330 is out of bounds for axis 0 with size 1000` in `triangular_sample_compression_2d`:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/core/data/phd-data/python_environments/hera-system/lib/python3.10/site-packages/anesthetic/samples.py", line 344, in plot_2d
    self.plot(ax_, x, y, plot_type=plot_type, *args, **lkwargs)
  File "/home/stefan/core/data/phd-data/python_environments/hera-system/lib/python3.10/site-packages/anesthetic/samples.py", line 213, in plot
    return kde_contour_plot_2d(ax, x, y, weights=self.weights,
  File "/home/stefan/core/data/phd-data/python_environments/hera-system/lib/python3.10/site-packages/anesthetic/plot.py", line 818, in kde_contour_plot_2d
    tri, w = triangular_sample_compression_2d(data_x, data_y, cov,
  File "/home/stefan/core/data/phd-data/python_environments/hera-system/lib/python3.10/site-packages/anesthetic/utils.py", line 359, in triangular_sample_compression_2d
    np.add.at(w_, k[:, i], w[j != -1]/3)
IndexError: index 23211 is out of bounds for axis 0 with size 1000
```

This can be solved by adding a `reset_index()` to the merge, re-indexing the samples correctly 
```python
merge_prior = anesthetic.samples.merge_samples_weighted(prior_samples, weights=np.ones(51)).reset_index()
```
As soon as I get time I will make a PR to fix this bug.

*Note:* We use `df.append` in `merge_samples_weighted` which is now deprecated and we should replace that function as well.

**Comment by Stefan-Heimersheim** [comment]
There's another problem: `reset_index()` resets `merge_prior.weights` to 1, while `merge_prior["weights"]` is still correct. As quick fix I am using `merge_prior.weights = merge_prior["weights"]` now.

**Comment by williamjameshandley** [comment]
Hi @Stefan-Heimersheim. The weights problem looks like you are using quite an old version of anesthetic -- do you get this problem if you use the master branch? You can get this by installing:
```bash
pip install anesthetic==2.0.0b11
#or
pip install pip install git+https://github.com/williamjameshandley/anesthetic@master
```
(We plan to properly release anesthetic 2.0.0 over the summer once we've finalised all the interface-breaking changes).

I agree that we should replace the `df.append` functions however

**Comment by Stefan-Heimersheim** [comment]
I appear to have the latest version:
```
pip freeze | grep anesthetic
anesthetic @ git+https://github.com/williamjameshandley/anesthetic@5430098069d2fd4d33e0a0689a55b42563ad8f71
```
I just did `pip3 install anesthetic==2.0.0b11` on a different machine (calx) and ran my MWe and still got an `IndexError`

**Comment by Stefan-Heimersheim** [comment]
> If we want to go with reindexing it's a little bit more involved to ensure that the weights are passed on correctly.

Ah right, I had just added an `merge_prior.weights = merge_prior["weights"]`.

> If you agree, please go ahead and submit a PR with this minor change

Will do!
