### ISSUE TITLE
Create more general `Samples` that is parent to both `MCMCSamples` and `NestedSamples`

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#199]
Currently `MCMCSamples` is the parent of `NestedSamples`. For many things this works quite nicely, since `NestedSamples` tends to be the one with more features. However, there are a few things that are actually quite specific for `MCMCSamples`, e.g. coming from different chains. Hence, it would be nice to have a more general `Samples` class that is parent to both `MCMCSamples` and `NestedSamples`, and to have some MCMC specific functionality to the new `MCMCSamples`.

In that context, it would be nice to have the following MCMC features:
* Move the `burn_in` to the new `MCMCSamples` (has nothing to do with `NestedSamples`.
* Keep track of the chain number for each sample point (allows separating the complete dataset into separate chains).
* Have some functions for convergence statistics of MCMC chains.
* Others?

**Comment by williamjameshandley** [comment]
With this change in hierarchy, we should change the `ValueError` which currently occurs when trying to load `NestedSamples` as `MCMCSamples` to a warning, since there might be the occasional (highly unusual) use case where you wanted to treat the `NestedSamples` as `MCMCSamples`, but we could no longer legitimatey claim
```
ValueError: The file root ./tests/example_data/pc seems to point to a Nested Sampling chain. Please use NestedSamples instead which has the same features as MCMCSamples and more. MCMCSamples should be used for MCMC chains only.
```

**Comment by lukashergt** [comment]
> With this change in hierarchy, we should change the `ValueError` which currently occurs when trying to load `NestedSamples` as `MCMCSamples` to a warning, since there might be the occasional (highly unusual) use case where you wanted to treat the `NestedSamples` as `MCMCSamples`, but we could no longer legitimatey claim
> 
> ```
> ValueError: The file root ./tests/example_data/pc seems to point to a Nested Sampling chain. Please use NestedSamples instead which has the same features as MCMCSamples and more. MCMCSamples should be used for MCMC chains only.
> ```

Was your second mention of `MCMCSamples` meant to be `Samples`? 
Would we still want and error for the new `MCMCSamples`?
