### ISSUE TITLE
Travis cleanup

### ISSUE THREAD

**Issue by williamjameshandley** [williamjameshandley/anesthetic#20]
The .travis.yml build matrix now getting rather large, particularly as #15 is about to be merged.

I have a few questions for @lukashergt 

1. Do we need to test against two versions of montepython?
2. Do we need the ``MPLBACKEND=Agg`` in light of #17?

Once these questions are answered, I can have a go at simplifying the build matrix so that it's laid out more logically, and hopefully is a little faster.

**Comment by lukashergt** [comment]
1. I put in two versions as MontePython is an actively evolving code, so changes to MontePython's master might eventually lead to anesthetic's tests failing. Checking a stable release version would point this out instantly. But it's probably enough to cross check a stable release version only once.

2. Is that exactly what `MPLBACKEND=Agg` is doing, just setting the backend to 'Agg'? Then yes #17 should be taking care of that. Removing this won't decrease the number of tests, though, right?

**Comment by williamjameshandley** [comment]
> Is that exactly what MPLBACKEND=Agg is doing, just setting the backend to 'Agg'? Then yes #17 should be taking care of that. Removing this won't decrease the number of tests, though, right?

Yes, so that should clean it up a bit.

>I put in two versions as MontePython is an actively evolving code, so changes to MontePython's master might eventually lead to anesthetic's tests failing. Checking a stable release version would point this out instantly. But it's probably enough to cross check a stable release version only once.

In general, it's not good practice to guarantee support for evolving code. Better to say that it works with 3.10, and the update it otherwise. One could have a single test that is allowed to fail to check that it works with master, and raise an issue if/when that fails.

**Comment by lukashergt** [comment]
> One could have a single test that is allowed to fail to check that it works with master, and raise an issue if/when that fails.

That sounds good. For people that intend to keep up with the evolving code that will catch the issue quicker.
