### ISSUE TITLE
Consider removing user ability to set `.limits`

### ISSUE THREAD

**Issue by williamjameshandley** [williamjameshandley/anesthetic#200]
One of the interfacing problems in #105 is that we would rather encourage users to set limits at the prior level by importance sampling (e.g. `samples.importance_sample(samples.x0>0, action='mask')`) in comparison with setting the `.limits`, which should in principle be extractable purely from the samples themselves. We would propose to remove the `.limits` and at the very least replace with `._limits`

**Comment by lukashergt** [comment]
It would also be good to crack the anesthetic plotting limits once and for all, i.e. automatically determine the appropriate plotting range that 
a) ensures that only the relevant bits get plotted, i.e. all non-transparent things, and not crazy long tails,
b) to that end it needs to reliably compute the important plotting range (difficult case being e.g. multimodal distributions),
c) and upon adding a second set of samples to a first set, the plot range should be only expanded, and should not loose the first plots.
