### ISSUE TITLE
Should we change the way we read files?

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#208]
Our current way of reading chain files (be it from PolyChord, MultiNest, Cobaya, ...) is not how pandas would do it. In pandas you use functions such as `pandas.read_csv`. 

* Should we have an `anesthetic.read` function? 
* Should it be just `anesthetic.read` or more specifically `anesthetic.read_polychord`, `anesthetic.read_multinest`, etc. or yet rather `anesthetic.read_mcmc` and `anesthetic.read_ns`?

**Comment by williamjameshandley** [comment]
Unless anybody objects, we should go with the philosophy of 'make it look more like pandas' (the third option would be to use `@classmethod`s and have `samples = NestedSamples.read(root)`, but this is not what pandas does, and I now seem to be remembering that when I tried this it did not gel well with subclassing `DataFrame`s. 

Another virtue of `read_chains` would be that it would simplify the `__init__` functions to make it easier for future users to modify.
