### ISSUE TITLE
change `fig, axes` output to just `axes`?

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#223]
Should we be changing the our plotting output from `fig, axes` to only `axes`?

There are two different places to think about this:
1) the output from `make_1d_axes` and `make_2d_axes`.
2) the output from `samples.plot_1d` and `samples.plot_2d`.

**Comment by lukashergt** [comment]
> 1) the output from `make_1d_axes` and `make_2d_axes`.

This is related to #203. Currently I will often write:
```python
fig = plt.figure(figsize=(10, 10))
fig, axes = make_2d_axes(['x0', 'x1'], fig=fig)
```

I would want to keep the `fig, axes` output for `make_1d_axes` and `make_2d_axes`, but ensure that they both accept all the kwargs you would want to pass to `plt.figure()`, such that there is no need for the first line in my example.


&nbsp;

> 2) the output from `samples.plot_1d` and `samples.plot_2d`.

In this case I don't have that clear an opinion. The main reason for that is that I typically don't bother with the output from these. I tend to use `make_1d_axes` and `make_2d_axes` to set up my figure and axes, and then I simply pass the axes on:
```python
fig, axes = make_2d_axes(['x0', 'x1'])
samples1.plot_2d(axes)
samples2.plot_2d(axes)
```

Returning only `axes` would make things slimmer, but on the other hand there is something to be said for returning the same as `make_1d_axes` and `make_2d_axes`.

**Comment by williamjameshandley** [comment]
My initial view would be that
1. `make_nd_axes` should retun `fig, axes` (consistent with plt.subplots(), with no real equivalent in pandas)
2. `samples.plot...` should return `axes` (consistent with `df.plot`)

My usual use-case (where I don't need fine-grained `make_nd_axes` control) is:
```python
axes = ['x0', 'x1', 'x2']
fig, axes = samples1.plot_2d(axes)
fig, axes = samples2.plot_2d(axes)
```
which would now become:
```python
axes = ['x0', 'x1', 'x2']
axes = samples1.plot_2d(axes)
axes = samples2.plot_2d(axes)
```
The reason for collecting the output is that it's then very easy to rearrange the order of plotting without a `make_2d_axes` command.

The disadvantage of dropping the `fig` output is that it's a bit of a faff to collect `fig = ax.iloc[0,0].figure`, but this would also be true of `pandas`.

I think that we should definitely forward on all extra kwargs to the `plt.figure` command, as this is what [`plt.subplots`](https://github.com/matplotlib/matplotlib/blob/v3.5.3/lib/matplotlib/pyplot.py#L1319-L1457) does too.

Are there any API changes we would like to make? Reading over the code I think I could probably make some of it neater
- I don't think one needs to precompute a `position` array, and it would be cleaner with a function
- If this were a separate function, we could do away with the `.position` attributes monkey patched onto the axes themselves
- This kind of functionality could be moved into the existing `AxesDataFrame` class

The main API I would like to discuss is whether we move the `make_2d_axes` code into a constructor for `AxesDataFrame` (but retain the helper function `make_2d_axes` as well). The same goes for `AxesSeries` and `make_1d_axes`. This would hopefully help to break up the 'wall of code' that these functions currently are.
