### ISSUE TITLE
incorrect minor ticks appearing with the 2.0.0 upgrades

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#229]
In the current master version there are minor tick marks appearing that do not match the major tick marks, which are formatted using `set_major_locator`.

MWE:
```python
import matplotlib.pyplot as plt
from anesthetic import read_chains, MCMCSamples, NestedSamples, make_1d_axes, make_2d_axes

ns1 = read_chains("/home/lthergt/Documents/Projects/AnestheticPrj/anesthetic/tests/example_data/pc")
params = ["x0", "x1", "x2"]
fig = plt.figure(figsize=(5, 5))
fig, axes = make_2d_axes(params, fig=fig);
ns1.plot_2d(axes);
```

![image](https://user-images.githubusercontent.com/18258042/189518995-60527d13-ee85-43cb-82cb-ceef034baa2c.png)

How would we prefer handling this? 

1) Set minor tick length to zero? (very easy)
   This could be done in the spirit of "If you really want something as complicated as minor tick marks in a triangle plot, then you'll have to set them manually".
   
2) Try to match the minor tick mark handling to that of the major tick marks?
   This would be more in line with our "match default matplotlib/pandas behaviour" philosophy...

3) Change the major tick mark handling to avoid the problem?
   For example rotate tick labels by 45 degrees such that the default matplotlib tick labels potentially fit, and then we drop the `set_major_locator`. Other suggestions?

**Comment by williamjameshandley** [comment]
3 is also consistent with "match default matplotlib/pandas behaviour", i.e. don't mess around with the ticks beyond rotating them.

(`fig._autofmt_xdate()`](https://matplotlib.org/3.3.4/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.autofmt_xdate) could be the recommended way to rotate all the xtick labels (and indeed we could call this once at the end by default).
