### ISSUE TITLE
NestedSamples constructor error when root supplied as single positional argument

### ISSUE THREAD

**Issue by andrewfowlie** [williamjameshandley/anesthetic#241]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the following doesn't work and gives a cryptic error
  
     >>> from anesthetic import NestedSamples
     >>> NestedSamples('whatever/the/root/is')
     ValueError: DataFrame constructor not properly called!

after a little bit of thinking I correctly do

    NestedSamples(root='whatever/the/root/is')

In the first case, the `root` argument is passed on to the WeightedDataFrame object via `*args`, which causes the error. This probably applies also to the MCMCSamples parent class.

**Describe the solution you'd like**

1. Ideally, interpret the first example as a root keyword.  However, this gets complicated because of the positional arguments in the current `(self, *args, **kwargs)` signature of the constructor. We can't just do

        def __init__(self, root=None, *args, **kwargs)

as root will gobble one of the positional `*args` that a user might try to pass. I don't know the intended usage of the positional arguments, but it seems useful to be able to pass them on.

2. So maybe them just catching and re-raising the exception with something more informative. 
3. More radically, currently the `root` keyword seems to be a completely different way of constructing the object. And it could already be confusing. The docs say `Overrides all other arguments.` but that doesn't seem to be quite true, as even with root one or two kwargs are still popped. Certainly some other kwargs are ignored/overridden. And the docs somewhat indicate that my first attempt `NestedSamples('whatever/the/root/is')` might work because root seems to be the first argument in the constructor.

So perhaps another solution is a staticmethod second constructor

    @staticmethod
    def FromRoot(cls, root, **kwargs):

and abolishing the kwargs root from the default __init__ constructor.

**Comment by williamjameshandley** [comment]
Hi @andrewfowlie. With the upcoming 2.0.0 release, we have reverted to a more pandas-like initialisation #217. This removes the root keyword argument. The way to load from file is now:

```python
from anesthetic import read_chains

read_chains('/whatever/the/root/is'

```

**Comment by andrewfowlie** [comment]
Thanks Will. I think this is a really good design decision, it seems like it addresses my issue here and a has other advantages
