### ISSUE TITLE
Return values in plot_2d

### ISSUE THREAD

**Issue by yallup** [williamjameshandley/anesthetic#257]
A pattern I had previously used a lot that now appears broken was to call plot_2d on a chains file with the names of the axes to plot and create the figure and axes from that, e.g.

```python
f,a=chains.plot_2d(axes_to_plot,kinds=dict(lower='kde_2d'),label="Post",lower_kwargs = dict(alpha=0.8,label="Post"))
```

As of the changes in

https://github.com/williamjameshandley/anesthetic/blob/57a1afda2e2123afb9ff8c6bbd8325936b3ca152/anesthetic/samples.py#L292

This no longer works (only return axes). I'm questioning whether the fallback call to make_2d_axes embedded in plot2d should still exist? Perhaps I am missing a mpl trick but with the figure thrown away I don't naively know how to interact with it, so maybe this is a usage pattern that is now discontinued?

**Comment by williamjameshandley** [comment]
This decision was made in #223 in our ongoing attempts to maintain 
consistency/align with pandas conventions.

>Perhaps I am missing a mpl trick but with the figure thrown away I don't naively know how to interact with it, so maybe this is a usage pattern that is now discontinued?

```python
ax = chains.plot_2d(...)
fig = ax.get_figure()
# or
fig = ax.figure
```

**Comment by lukashergt** [comment]
My recommended way of doing this is by calling `make_2d_axes` yourself (see also [the Quickstart page in the docs](https://anesthetic.readthedocs.io/en/latest/quickstart.html)). Think of it similar to standard matplotlib syntax: one line to set up figure and axes, and the next to actually plot.

```python
from anesthetic import make_2d_axes
fig, axes = make_2d_axes(axes_to_plot, upper=False, diagonal=False)
chains.plot_2d(axes, kinds=dict(lower='kde_2d'), alpha=0.8, label="Post")
```

**Comment by yallup** [comment]
Thanks both, I'll close this as I think both solutions are sound, probably best to align with the more complete explicit use of make_2d_axes going forward as that seems to match the mpl style best
