### ISSUE TITLE
`WeightedDataFrame.groupby.mean` does not produce weighted means

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#260]
## Describe the bug

There are two tiers to this bug:
1. Currently the means (and other statistics) after a pandas `groupby` method call from a `WeightedDataFrame` are not weighted means . The weights are being ignored. 
2. The groups themselves should be weighted objects (sum of weights within the group), such that the mean of the group mean matches the overall sample mean. So we need some sort of `WeightedGroup` object, such that weights are taken into account when performing between-group statistics.

## To Reproduce

```python
import numpy as np
from anesthetic.samples import Samples

params = ['a', 'b']
data = np.random.rand(4, 2)
weights = np.random.randint(1, 10, 4)
samples = Samples(data, weights=weights, columns=params)
samples['group'] = np.ones(4, dtype=int)
samples.loc[2:, 'group'] = 2

group1_means  = np.average(samples.loc[:1, params], axis=0)
group1_wmeans = np.average(samples.loc[:1, params], axis=0, weights=samples.get_weights()[:2])
group2_means  = np.average(samples.loc[2:, params], axis=0)
group2_wmeans = np.average(samples.loc[2:, params], axis=0, weights=samples.get_weights()[2:])
group_means  = np.vstack([group1_means,  group2_means])
group_wmeans = np.vstack([group1_wmeans, group2_wmeans])
group_weights = [samples.get_weights()[:2].sum(), samples.get_weights()[2:].sum()]
mean =  np.average(group_means,  axis=0)
wmean = np.average(group_wmeans, axis=0, weights=group_weights)
```

## Expected behavior

The mean values after a groupby call should be weighted means; however, currently the weights are being ignored.

```python
assert not np.any(samples.groupby('group').mean() == group_means)
assert np.all(samples.groupby('group').mean() == group_wmeans)
```

Furthermore, the mean of the group means should match the overall sample mean:

```python
assert not np.any(samples.groupby('group').mean().mean() == mean)
assert np.all(samples.groupby('group').mean().mean() == wmean)
```

## Additional context

This follows up from the discussion in https://github.com/williamjameshandley/anesthetic/pull/258#discussion_r1099617574, and as such is relevant for the accurat computation of the Gelman--Rubin statistic. In that comment we also discussed the potential issue of having missing values.

## Screenshots

![image](https://user-images.githubusercontent.com/18258042/217930226-5f8c898d-3503-4d29-8e3f-7288efc461ec.png)

**Comment by Ormorod** [comment]
@lukashergt just in case this is relevant, `numeric_only=False` is the new default in [pandas 2](https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.cov.html)

**Comment by Ormorod** [comment]
The arguments of our `cov` also don't match pandas, which isn't working with pandas 2.

**Comment by Ormorod** [comment]
Thinking aloud, this might be a good thing, as it might mean that the correct covariance function is actually being called...

**Comment by lukashergt** [comment]
In `cov` it checks whether the data frame is weighted or not. If unweighted, it should work like the pandas one. If weighted, then you shouldn't provide the same kwargs as with the pandas one, e.g. `ddof` is not needed with weighted data. 

So I think this is mostly fine, although we probably could unify the two a bit more, and since the weighted `cov` has different kwargs to the unweighted one, we probably shouldn't be inheriting the docs in this case...

**Comment by Ormorod** [comment]
I've noticed that if one uses e.g.
```
samples.groupby('group').get_group(1).mean()
```

Then the weighted mean is used.

**Comment by Ormorod** [comment]
> In `cov` it checks whether the data frame is weighted or not. If unweighted, it should work like the pandas one. If weighted, then you shouldn't provide the same kwargs as with the pandas one, e.g. `ddof` is not needed with weighted data.

That makes sense, but is going to be a pain to make it work. I've been looking at the groupby pandas code a lot today, and `DataFrameGroupBy` and `SeriesGroupBy` both have a lot of hard-coded `return DataFrame(...)`/`return Series(...)`. I'll have a look into whether I think this is PR-able with a splattering of `_constructor()`s

> So I think this is mostly fine, although we probably could unify the two a bit more, and since the weighted `cov` has different kwargs to the unweighted one, we probably shouldn't be inheriting the docs in this case...

I've a funny feeling this isn't the first time we've talked about the docstring of cov...

**Comment by lukashergt** [comment]
> I've noticed that if one uses e.g.
> 
> ```
> samples.groupby('group').get_group(1).mean()
> ```
> 
> Then the weighted mean is used.

Yes, `get_group` essentially returns a slice from the original data frame, which will still be a `WeightedDataFrame`. Unfortunately it looks like that is not used when calling `mean` on the `DataFrameGroupBy` object...

> I've been looking at the groupby pandas code a lot today, and `DataFrameGroupBy` and `SeriesGroupBy` both have a lot of hard-coded `return DataFrame(...)`/`return Series(...)`. I'll have a look into whether I think this is PR-able with a splattering of `_constructor()`s

Ugh, that sounds like it might indeed be more a problem with the pandas implementation rather than ours... that is unfortunate...

**Comment by Ormorod** [comment]
It looks like this has been looked into [before](https://github.com/pandas-dev/pandas/pull/33884), hopefully this means fixing again might not be _too_ difficult

**Comment by lukashergt** [comment]
> It looks like this has been looked into [before](https://github.com/pandas-dev/pandas/pull/33884), hopefully this means fixing again might not be _too_ difficult

Hmm, this makes me wonder why [`test_groupby_preserves_subclass`](https://github.com/pandas-dev/pandas/blob/main/pandas/tests/groupby/test_groupby_subclass.py) didn't catch this...

**Comment by Ormorod** [comment]
I've spent another day looking into this; after replacing myriad `Series`/`DataFrame` with appropriate constructors, `samples.groupby('group').mean()` eventually uses a cython backend regardless, which I'm struggling to see how to change...

However this time yesterday I didn't think I'd get this far, so I'll keep going

**Comment by lukashergt** [comment]
> As I understand it, these tests check that the returned types (from e.g. `get_group()`) are appropriate, and that metadata is preserved, but it contains no checks to assert that e.g. overriding `mean()` actually works.

Ah yes, that is probably the issue. Not only did we subclass `DataFrame` but our subclass also overwrites the `mean` method...

**Comment by Ormorod** [comment]
This is my mwe:
```
import numpy as np
import pandas as pd

class UnitSeries(pd.Series):
    @property
    def _constructor(self):
        return UnitSeries

    @property
    def _constructor_expanddim(self):
        return UnitDataFrame

    def mean(self, *args, **kwargs):
        print("UnitSeries mean")


class UnitDataFrame(pd.DataFrame):
    @property
    def _constructor(self):
        return UnitDataFrame

    @property
    def _constructor_expanddim(self):
        return UnitSeries

    def mean(self, *args, **kwargs):
        print("UnitDataFrame mean")
        return 1


params = ['a', 'b']
data = np.random.rand(4, 2)
udf = UnitDataFrame(data, columns=params)
udf['group'] = np.ones(4, dtype=int)
udf.loc[2:, 'group'] = 2

if __name__ == "__main__":
    print(udf.mean()) # prints 1 :)
    print(udf.groupby('group').mean()) # not a 1 to be seen :(
```

**Comment by Ormorod** [comment]
> > As I understand it, these tests check that the returned types (from e.g. `get_group()`) are appropriate, and that metadata is preserved, but it contains no checks to assert that e.g. overriding `mean()` actually works.
> 
> Ah yes, that is probably the issue. Not only did we subclass `DataFrame` but our subclass also overwrites the `mean` method...

I believe this applies to literally every method, as it is the method of `DataFrameGroupBy` which is called, which knows little about our subclass. For the same reason, new methods don't work with `groupby()`
```
import numpy as np
import pandas as pd

class UnitSeries(pd.Series):
    @property
    def _constructor(self):
        return UnitSeries

    @property
    def _constructor_expanddim(self):
        return UnitDataFrame

    def mean(self, *args, **kwargs):
        print("UnitSeries mean")
        return 1

    def beans(self, *args, **kwargs):
        return "series toast"


class UnitDataFrame(pd.DataFrame):
    @property
    def _constructor(self):
        return UnitDataFrame

    @property
    def _constructor_expanddim(self):
        return UnitSeries

    def mean(self, *args, **kwargs):
        print("UnitDataFrame mean")
        return 1

    def beans(self, *args, **kwargs):
        return "df toast"



params = ['a', 'b']
data = np.random.rand(4, 2)
udf = UnitDataFrame(data, columns=params)
udf['group'] = np.ones(4, dtype=int)
udf.loc[2:, 'group'] = 2

if __name__ == "__main__":
    print(udf.mean()) # prints 1 :)
    print(udf.groupby('group').mean()) # not a 1 to be seen :(
    print(udf.beans()) # prints "df toast"
    print(udf.groupby('group').beans()) # AttributeError
```
The last line causes
```
AttributeError: 'DataFrameGroupBy' object has no attribute 'beans'. Did you mean: 'mean'?
```

**Comment by lukashergt** [comment]
I normally go with spam, ham, and eggs, but beans on toast is good, too...^^

**Comment by Ormorod** [comment]
I've got the first three assertions from your example working, just the weighted mean of weighed means broken (and the small matter of fixing every single other operation).

**Comment by lukashergt** [comment]
> I've got the first three assertions from your example working, just the weighted mean of weighed means broken (and the small matter of fixing every single other operation).

That sounds great!! 

The weighted mean of weighted means is probably an anesthetic thing rather than a pandas thing. Not only are the groups each a `WeightedDataFrame`, but there is also a weight associated with each group, which should be the sum of all weights within the group (possibly normalised such that the sum of the group weights equals 1). 

In fact, this could go wrong even for initially unweighted samples. Also in that case should the means of each group have a weight, which is essentially the number of samples in each group.

**Comment by Ormorod** [comment]
Agreed that the weights are our problem to solve, not pandas. We need to think carefully about what exactly should be returned from groupby(), and I think this is where our own `WeightedGroupBy` will come in (and hopefully allow me to slot in the changes I send off to pandas in the meantime). 

However, I don't expect pandas to accommodate our changing of the signature of `cov()` (or anything else, if you happen to know which methods have been changed that would be v helpful!). I **think** just implementing `WeightedGroupBy.cov()` will work, but I will need to think carefully about the inheritance structure.

**Comment by Ormorod** [comment]
Have also got `median()`, `std()`, `var()`, `sem()`, `prod()`, `sum()`, `min()` and `max()` working in `pandas.core.groupby.GroupBy()`with essentially the same fix, and I think I will have to yield to a pandas expert to know if more needs to be done. 

Incidentally, `DataFrameGroupBy.cov()` already uses the subclass method, so the issue there is just the signature change.

I've created issue [#51757](https://github.com/pandas-dev/pandas/issues/51757), will try get a PR ready by the end of today.
