### ISSUE TITLE
Is the mirroring flag `f` in `kde_?d` wrong? 

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#29]
In `kde_1d` the data is mirrored to help with boundary conditions:

```python
def kde_1d(d, xmin=None, xmax=None):
    """Perform a one-dimensional kernel density estimation."""
    xmin, xmax = check_bounds(d, xmin, xmax)
    f = xmax is None or xmin is None
    d_ = mirror_1d(d, xmin, xmax)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        p, x = fastKDE.pdf(d_, axisExpansionFactor=f,
                           numPointsPerSigma=10*(2-f))
    p *= 2-f

    if xmin is not None:
        p = p[x >= xmin]
        x = x[x >= xmin]

    if xmax is not None:
        p = p[x <= xmax]
        x = x[x <= xmax]

return x, p
```

Shouldn't `f` be true if _no_ boundaries exist? Meaning:
```python
    f = xmax is None and xmin is None
```

Same goes for the 2D case.

From a plotting perspective this is irrelevant I think, since p gets renormalised as `p /= p.max()` anyhow, but probably nicer to make sure `kde_?d` make sense on their own.

**Comment by williamjameshandley** [comment]
Is this issue still relevant in the latest version of anesthetic?

**Comment by lukashergt** [comment]
I think this was still prior to `gaussian_kde` and concerned mirroring at boundaries, which we aren't doing anymore. I'll close it.
