### ISSUE TITLE
MCMCSamples cannot read nested sampling output files correctly.

### ISSUE THREAD

**Issue by xichenamoy** [williamjameshandley/anesthetic#37]
Happened when execute this line:

sample = MCMCSamples(root=fileName)

Then get this error message:

ValueError: DataFrame constructor not properly called!

One thing worth to note is that 1.1.0 works well with the provided lensing example. So the error only happens when I change the 'root' equals to my own file name in the chains folder.

I also tried the standard PolyChord output file using the default gaussian example, it would report:

ValueError: Wrong number of items passed 5, placement implies 1

Previously when I used it with anesthetic 1.03, it can read the file ok. Now I upgraded it to version 1.1.0, run the same code it would report this.  The output files are the standard MultiNest/PolyChord output files.

**Comment by williamjameshandley** [comment]
Hi @xichenamoy . Many thanks for spotting this. 

Can you confirm that this only occurs if you try to use read nested sampling chains with `MCMCSamples`, and that reading them with `NestedSamples` does not have this issue?

@lukashergt, I think this was introduced in #14 when we restructured in terms of `SampleReader`. It might be worth just raising a more informative `ValueError` if one tries to read ns chains with `MCMCSamples`

**Comment by xichenamoy** [comment]
@williamjameshandley 
Yes, I forgot to mention this. It works well with NestedSamples(), only occurs in MCMCSamples().

**Comment by lukashergt** [comment]
> I think this was introduced in #14 when we restructured in terms of `SampleReader`

Probably, I never checked for the option of reading nested sampling files with `MCMCSamples`. Is that what we want?

**Comment by williamjameshandley** [comment]
I'm not sure. In theory NS files should be readable as MCMCSamples, but I don't know why you'd want to/if we should encourage it. Given that NestedSamples is a subclass of MCMCSamples you would get no benefit from loading them as MCMCSamples, so at the very least if we want to allow people to do this we should throw a warning. For now, the easiest solution would be to not support reading MN/PC files with MCMCSamples, but to throw a more informative error.

**Comment by lukashergt** [comment]
Fixed in #64
