### ISSUE TITLE
Automatic labelling

### ISSUE THREAD

**Issue by williamjameshandley** [williamjameshandley/anesthetic#42]
@lukashergt latest fix for figure legends #30 means that we now have matplotlib-like handles for creating figure legends. However, these are only applied if you supply a label keyword argument to the plot. It might be better if this was automatically generated/could be set as a member variable for MCMCSamples, so that users didn't need to remember to supply labels to generate plots.

**Comment by lukashergt** [comment]
Maybe use the variable name of the `MCMCSamples` instance as default value for the label?

Then again it might be enough to make `label` an explicit arg/kwarg (with `None` as default) such that it pops up in the docs. Added an item to the to-do list in #24.

**Comment by williamjameshandley** [comment]
I think using instance variable names might be [pretty frowned upon/very challenging](https://stackoverflow.com/questions/1690400/getting-an-instance-name-inside-class-init). I was thinking of using the basename if a root file is provided. An explicit `label` kwarg would then override this/provide functionality if you're building an instance manually. 

Probably best to to put this in as a separate PR, rather than in #24, which is more documentation related.
