### ISSUE TITLE
Calculating model dimensionality from MCMC run

### ISSUE THREAD

**Issue by Pablo-Lemos** [williamjameshandley/anesthetic#48]

**Comment by lukashergt** [comment]
Hi Pablo,

not sure what exactly you are going for here... (Was this accidentally sent off?)

But inferring the question from the title, a quick way of estimating the bayesian model dimensionality from an MCMC run is through:
```python
def bayesian_model_dimensionality(sample):
    mode1 = np.average(sample.logL.values, weights=sample.weight.values)
    mode2 = np.average(sample.logL.values**2, weights=sample.weight.values)
    return 2 * (mode2 - mode1**2)
```

**Comment by williamjameshandley** [comment]
Or alternatively
```python
2*sample.logL.var()
```

**Comment by williamjameshandley** [comment]
Although having tried this, it seems there is an error in the data files for the example data gd, associated with the fact that getdist format assumes the loglikelihood column is `-2*logL`. I'll correct this now.

**Comment by williamjameshandley** [comment]
> Or alternatively
> 
> ```python
> from anesthetic import MCMCSamples
> samples = MCMCSamples(root='./tests/example_data/gd')
> 2*samples.logL.var()
> ```
> 
> since `MCMCSamples` is a derived type of `WeightedDataFrame`, which is a derived type of `pandas.DataFrame` for weighted samples

@Pablo-Lemos Does the code `d = 2*samples.logL.var()` address your needs, or do you think we need an explicit model dimensionality function?

**Comment by Pablo-Lemos** [comment]
That looks okay to me
