### ISSUE TITLE
Best strategy for selecting a certain parameter range? Allow mask?

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#53]
I would like to select a certain parameter range and then plot the contours for this selection, e.g. say I'd like to look at only positive x0 with the example data:
```python
ns = NestedSamples(root="/scratch/Projects/AnestheticPrj/anesthetic/tests/example_data/pc")
fig = plt.figure(figsize=(7, 7))
fig, axes = make_2d_axes(['x0', 'x1'], fig=fig, upper=False)
ns.plot_2d(axes=axes, label='foo')
axes.iloc[-1, 0].legend(bbox_to_anchor=(len(axes), len(axes)), loc='upper right')
```
![image](https://user-images.githubusercontent.com/18258042/64551053-25efb900-d32c-11e9-9a9c-0caa76f6cc8e.png)

It is easy to create a mask for a specific parameter range:
```python
mask = ns['x0'] > 0
```
A table with the selected data can be displayed simply by:
```python
ns[mask]
```

However, the anesthetic specific functions can't be applied to this, i.e. exchanging `ns` for `ns[mask]` in the above code doesn't work but fails with:
```bash
ValueError: weights should have the same shape as x
```

This means while the mask is applied to the parameters (e.g. self['x0'], but also self['weight']!) it is not applied to the array `self.w` (and `self.u`?). 

I see two possible solutions here:

1) Might it possibly be better to be working internally with `self['weight']` instead of `self.w`? (And analogously for `self.logL`, `self.u` etc.) Could that be enough to make masking work as described above?

2) We could introduce a `mask` kwarg to the plotting functions?

**Comment by williamjameshandley** [comment]
Does #55 fix your issues?

**Comment by williamjameshandley** [comment]
Ah, I see you have also proposed #54 .

The main reason that we can't use 'weights' to define weights is that we need the `w` to be more fundamental than a column, in particular for performing operations like `samples.x0.mean()`. When slicing `samples.x0`, the `weights` column is not passed on to a series.

**Comment by lukashergt** [comment]
#55 doesn't quite fix this, but I could fetch the necessary changes from #54 and include them in #55? Shall I also fetch the unit test I made there?

**Comment by lukashergt** [comment]
> The main reason that we can't use 'weights' to define weights is that we need the w to be more fundamental than a column, in particular for performing operations like samples.x0.mean(). When slicing samples.x0, the weights column is not passed on to a series.

We only need `w` to be more fundamental than a column for `WeightedSeries` where we don't (can't) have a designated `weight` column. Other than that (i.e. for `WeightedDataFrame`) wouldn't it be more transparent to keep the `weight` column and use this throughout instead of the `w` metadata? We could add a column for `u`, too (maybe name it `rand` or `randnum`?).

**Comment by williamjameshandley** [comment]
>We only need w to be more fundamental than a column for WeightedSeries where we don't (can't) have a designated weight column.

Sadly this isn't quite true. If one wanted slice across columns, say to compute a parameter mean `samples[['A','B']].mean()`, then users would have to explicitly pass the `weight` column every time.

> Other than that (i.e. for WeightedDataFrame) wouldn't it be more transparent to keep the weight column and use this throughout instead of the w metadata?

For backward compatibility purposes I agree that this is a sensible thing to do. However, it is a duplication of information, and issues could arise if people tried to importance sample by adjusting the `weight` column, rather than the `w` one. This is a tricky one. The latest push reinstates this, but I think it requires further discussion

> We could add a column for u, too (maybe name it rand or randnum?).

My fear is that this would add clutter and confusion. It really is an implementation-specific quantity for making neater dynamic plots and consistent compression. Perhaps we could keep it as an underscored variable? (the latest push also does this)

**Comment by williamjameshandley** [comment]
> #55 doesn't quite fix this, but I could fetch the necessary changes from #54 and include them in #55? Shall I also fetch the unit test I made there?

Many thanks for doing this.

**Comment by lukashergt** [comment]
> Sadly this isn't quite true. If one wanted slice across columns, say to compute a parameter mean `samples[['A','B']].mean()`, then users would have to explicitly pass the `weight` column every time.

Why shouldn't this be possible to do in the same way as done in `WeightedDataFrame` with `self.w` replaced by the column `self['weight']` itself (or the automatically associated attribute `self.weight`)? `samples[['A','B']].mean()` would be redefined in the same way, just using `self.weight` instead of `self.w`.

I still think this might be possible, however, fiddling around with it a bit I've been struggling with the order of reading in the weights from the table, creating a WeightedDataFrame from the tabe, and adding the weights back to the DataFrame. I think it could work by passing `weight` as part of the data to WeightedDataFrame.

But maybe it's easiest with creating a separate `self.w`, so I agree that it might be best to leave it as is. 

> For backward compatibility purposes I agree that this is a sensible thing to do. However, it is a duplication of information, and issues could arise if people tried to importance sample by adjusting the `weight` column, rather than the `w` one. This is a tricky one. The latest push reinstates this, but I think it requires further discussion

I agree that it's a duplication of information which is why I was wondering whether it might be better to get rid of `self.w` entirely and use `self.weight` (which accesses the column) instead. I think there is something to be said in favour of having the pandas table reflect the chains files.

> My fear is that this would add clutter and confusion. It really is an implementation-specific quantity for making neater dynamic plots and consistent compression. Perhaps we could keep it as an underscored variable? (the latest push also does this)

Agreed, I actually prefer how you hid the `u` deeper in the code. Still dislike the name, though.^^

**Comment by williamjameshandley** [comment]
>Why shouldn't this be possible to do in the same way as done in WeightedDataFrame with self.w replaced by the column self['weight'] itself (or the automatically associated attribute self.weight)? samples[['A','B']].mean() would be redefined in the same way, just using self.weight instead of self.w.

In your scheme, if `samples.columns` originally was `['A','B','C','weight']`, then `samples.mean()` would work fine. However `samples[['A','B']]` would only have columns `['A','B']`, because the `'weight'` column has been sliced away. When one computed a mean the weights wouldn't be used

>Still dislike the name, though.^^

Now would be the time to propose a better one!

**Comment by lukashergt** [comment]
> In your scheme, if `samples.columns` originally was `['A','B','C','weight']`, then `samples.mean()` would work fine. However `samples[['A','B']]` would only have columns `['A','B']`, because the `'weight'` column has been sliced away. When one computed a mean the weights wouldn't be used

Ah, indeed, the slice looses all attributes associated with a column... 

> it is a duplication of information, and issues could arise if people tried to importance sample by adjusting the weight column, rather than the w one.

Could we _rename_ `self.w` to `self.weight` and set `self.weight = self['weight']`? Would that solve the issue? Would `self.weight` be mutable such that any adjusting of the weight column would also affect the attribute and would the attribute survive any slicing?

> Now would be the time to propose a better one!

`randnum`? Too long? `rdm`?

**Comment by williamjameshandley** [comment]
>Could we rename self.w to self.weight and set self.weight = self['weight']? Would that solve the issue? Would self.weight be mutable such that any adjusting of the weight column would also affect the attribute and would the attribute survive any slicing?

Rather remarkably that seems to work. It also has the attractive property of making the weights column read-only (which is desirable). Future extensions should possibly allow an 'importance sampling' update of the weights, but for now if users have to do this they can modify `_w` directly

>randnum? Too long? rdm?

How about `rand`

**Comment by lukashergt** [comment]
> How about `rand`

Was thinking about that one, too, but was worried it might be confused with numpy's or scipy's versions of that name...? But I do prefer it over `u`, so I would be happy with it.
