### ISSUE TITLE
Overflow error because of Cobaya's definition of `logzero=-1e+300`

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#70]
Cobaya's definition of `logzero=-1e+300` causes Anesthetic to fail with an overflow error upon the calculation of the Bayesian dimensionality. The problematic lines are:

```python
S = (dlogX*0).add(self.logL, axis=0) - samples.logZ
samples['d'] = numpy.exp(logsumexp(logw, b=(S-samples.D)**2, axis=0))*2
```
When `S = -1e+300` then squaring `S` will cause an overflow error.

An easy fix would be to insert:
```python
S = S.where(S > -1e150, -1e150)
```

This can be easily done for the calculation of `d`, but I don't know whether we want to handle these extreme values for `logzero` further upstream?

**Comment by williamjameshandley** [comment]
Hi Lukas, whilst I agree that the solution proposed above (and provided in #71) does indeed locally fix the issue, I think a more permanent fix would be for anesthetic to allow different definitions of logzero, and adjust the chain accordingly. 

The cleanest way to do this would be to have an extra `logzero` kwarg to `NestedSamples.__init__`. Anesthetic would then check what the lowest death contour was, and change this value to the logzero provided. This would mean that chains produced by different samplers can be more easily compared like-for-like. I think if you can/should set `logzero` to default as `-numpy.inf`. The main reason for having `logzero` be anything else is that FORTRAN (which cosmomc and PolyChord are both written in) does not have a -INF that is reliable across architectures and compilers.

**Comment by lukashergt** [comment]
> I think that having `-numpy.inf` should fix all these issues, since it seems to work for the examples

The examples only have `-numpy.inf` in the `logL_birth` column, but the problem only arises when `logL` gets too small. Maybe worth extending the `pc` example data to include `-numpy.inf` values for `logL`?

`-numpy.inf` in `logL` is still problematic. While `logsumexp(logw)` can handle infinities, a weighted `logsumexp(logw, b=S)` will output `nans` when there are `-numpy.inf` in `logL`.

At this point we could
* use a small value such as `-1e30` instead of `-numpy.inf`
* use `-numpy.inf` and then somehow mask `logw` and `S` such that the `nan` terms are excluded?

**Comment by williamjameshandley** [comment]
Ah, I see. In principle, there shouldn't be any `-numpy.inf` values in the `logL` column, since they should be excluded in prior generation (although this is a somewhat controversial issue in terms of how one deals with equality of contour values is nested sampling). I do however see how this does not actually resolve the issue for the purposes of `d` calculation. With these observations, I think the most consistent way to deal with the `d` overflow issues is to mask them. One fix might be:

```python
samples['d'] = numpy.exp(logsumexp(logw+numpy.log((S-samples.D)**2), axis=0))*2
```
