### ISSUE TITLE
`inf` in limits breaks histogram plotting

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#78]
When `limits` are specified and contain `±inf`, then histogram plotting fails as it uses the limits to specify the ranges, which have to be finite.

* Should the limits (if not otherwise specified) generally be taken to be min and max of the sample instead of `±inf`?
* Else, should we catch infinities in the histogram plotting and replace them with min and max?

This might be something to include in #77 ?

**Comment by williamjameshandley** [comment]
This is also related to #36, which would be a much larger, but possibly quite useful and successful overhaul of the code. However I think it's a relatively straightforward change to the histogram code for now. Will update #77.

**Comment by lukashergt** [comment]
This got fixed in #77 but never closed. Closing now.
