### ISSUE TITLE
Confidence intervals within marginalised 1d plots. 

### ISSUE THREAD

**Issue by appetrosyan** [williamjameshandley/anesthetic#82]
This is a feature that's present in nestcheck, but not very convenient to use.  Anesthetic's main diagonal plots are useful as is, but providing the end user the ability to encode the errors in the posterior would be very nice to have, particularly in the `gui()`.

**Comment by williamjameshandley** [comment]
Convenience is always relative to a users experience with a code, but I agree that this should be brought into part of the wider nestcheck integration #63 discussion. A gui and manipulable version of the nestcheck plots would be truly awesome.

**Comment by appetrosyan** [comment]
The manipulable version would be too heavy. Or rather, to make it work, we'd need to refactor the GUI code. Particularly, I would suggest making the updates asynchronous, and non-blocking. To do it in a cross-platform way, we could use QML.

**Comment by williamjameshandley** [comment]
I agree that the gui is in heavy need of refactoring #33 in order to make it more consistent with the rest of anesthetic. We should definitely do this with possible future integrations in mind.

How well does QML integrate with python? I think we'd need quite a bit of justification to move away from a nominally 'pure python' code. At the moment anesthetic fits well within the scientific python ecosystem (numpy, scipy, pandas, matplotlib), so I'm hesitant to introduce dependencies that not all users might be expected to have (we have made efforts to remove more unusual packages like fastkde #66)

**Comment by appetrosyan** [comment]
Both follow from the same problem. The GUI, uses a Matplotlib canvas that is really bad at compositing renders. It's effectively a single large Qt widget, where anesthetic tries to place the plot elements by hand. 

If we did it with QtQuick Markup language (QML) we would get native widgets (e.g. buttons, checkboxes, comboboxes) that are properly aligned (the screenshot in readme has text larger than the buttons), and render more efficiently. It would also remove all code that composited the plots into the GUI, allow asynchronous updates, render on the GPU as well as allow other modes of interaction (e.g. context menus, list boxes)... This could also open the window to a front-end like Getdist-gui (but good). For example [matplotlib_qt_quick_playground](https://github.com/fcollonval/matplotlib_qtquick_playground)

So the move would imply writing a declarative GUI, (QML is a strict declarative subset of JavaScript). Python tells you how to render each plot individually. QML handles the layouts, and interactivity, tells Python when to re-plot the plots. The end user sees Pyside2 as an optional dependency (which they might have, as this is what getdist is using also), and a GUI with good responsiveness (at least it won't lock up when moving a slider). 

I would suggest opening a new issue for that though...

**Comment by williamjameshandley** [comment]
This does sound very interesting, and if we're going to overhaul the GUI then anything that improves both responsiveness and the quality of the layout is worth trying. I don't have any experience with QML, so perhaps this is something that @appetrosyan could start off as a more long-term project that several users could contribute to (myself included). We would start by creating a method `NestedSamples.GUI()` that offers an alternative to `NestedSamples.gui()`, the latter of which we could then deprecate and eventually remove.

I think the most basic functionality one would want to implement is a triangle plot for (e.g.) the first three parameters, with a slider that allows you to watch the live points evolve. Ideally you would use the NestedSamples.plot(...) functionality to draw, which would go some way to solving #33.

**Comment by appetrosyan** [comment]
Ok. Sounds good!

**Comment by williamjameshandley** [comment]
I believe this has been by @htjb in #145. Feel free to re-open if there is anything further
