### ISSUE TITLE
Possible anti-pattern with current weights behaviour

### ISSUE THREAD

**Issue by williamjameshandley** [williamjameshandley/anesthetic#86]
This issue arose from #84. The relevent text is copied, edited an collated from that PR for further discussion here @lukashergt, @appetrosyan

The code `samples['weight'][i] = 0` doesn't actually do anything, since `samples['weight']` is different from `samples.weight`, and it is the latter which is used for computing the weighted sums. This possible anti-pattern was introduced in #55 and #56. I'm not sure of the best way to ameliorate this clearly confusing state of affairs. One could:
- drop the weight as a column (but this then makes it less clear that it is a weighted frame)
    - @lukashergt : "I don't like this solution. It is useful to see the weight column when looking at the full table."
- make the weight column read-only (don't know if this is easy to do in pandas, and would likely cause no end of bother down the line)
   - @lukashergt : "Well, it seems like this is already the case, right? Trying to overwrite the weight column actually doesn't work..."
       - This is only partially true. It's worse than doing nothing, since users might think that they have done something when they haven't. [True read-only](https://stackoverflow.com/a/5541452) would raise an exception when a user tried to write to the column.
- synchronise the weight column with the weight attribute more effectively. This would require someone with an understanding of how the weighted data frames work in `anesthetic/weighted_pandas.py` which is currently just me at the moment (AFAIK).
    - It would be better practice if more than one person understood this portion of the codebase, otherwise the risk is increased that hidden bad behaviour is not being discovered.

------

The issue is that there is a hidden attribute in the `WeightedSeries` and `WeightedDataFrame` called `_weight`. 

The hidden attribute is necessary for `WeightedSeries`, as if you want the pandas equivalent of a `Series` you can only have one column, so the weights have to be an attribute. This is forwarded as a readable attribute via a `@property`, and the correct behaviour is also enforced for slicing.

The same was originally true for `WeightedDataFrame`, but this was slightly counterintuitive as you would not see the weights in the same way that you see `nlive` or other derived `NestedSamples` columns. The contents of `_weight` is therefore copied into a new column whenever you change `_weight` using the anesthetic functions, but if you go and change this new column manually it has no effect on the weighted calculations (like `mean`, `std`, `median` etc)
- synchronise the weight column with the weight attribute more effectively. This would require someone with an understanding of how the weighted data frames work in `anesthetic/weighted_pandas.py` which is currently just me at the moment (AFAIK).

**Comment by lukashergt** [comment]
Having looked a bit into the issue described in #95 I am wondering whether having the propery `weight` in `WeightedSeries` and `WeightedDataFrame` disjoint from the sample points might be complicating our lives unneccessarily...?

Each sample point comes with a corresponding weight, so having `weight` in the table with the parameter values and with `logL` etc. seems more natural to me, than keeping it as something separate. 

Were there reasons why we need to make that separation, @williamjameshandley?

**Comment by williamjameshandley** [comment]
The reason we need the separation is you still want it to be a weighted data frame if you do say `samples[['A','B']].mean()`, so you can't rely on a column of weights. The real issue is that it is also very convenient to be able to see this column of weights alongside the other columns (although strictly not necessary for weighted functionality), which is why this information is duplicated, and therefore prone to not being updated in parallel.

**Comment by lukashergt** [comment]
Keeping a column of weights, that example could be rephrased to:
```python
samples[['A', 'B']].mean(weight=samples.weight)  # weighted mean
samples[['A', 'B']].mean(weight=None)  # mean with equal weights
```
Where a required `weight` argument could enforce the weighted nature of the Series/Dataframe.

This could simplify our lives. Although, granted, this is not as nice and slim as what you suggest.

**Comment by lukashergt** [comment]
For brainstorming purposes. Maybe pandas' `MultiIndex` could be useful? That way we could have a secondary index which is our weights. This secondary weight index (all indices for that matter) gets displayed alongside the data, but also passed along to subsamples, slices, etc.


```python
import numpy as np
import pandas

index = np.arange(10)
weight = np.linspace(0, 1, index.size + 1)[1:]
indices = pandas.MultiIndex.from_tuples(zip(index, weight), names=['index', 'weight'])

params = ['x0', 'x1', 'x2', 'x3', 'x4']
data = np.arange(index.size * len(params)).reshape(len(params), index.size).T + 100

df = pandas.DataFrame(data, columns=params, index=indices)
```


```python
> print(df)

               x0   x1   x2   x3   x4
index weight                         
0     0.1     100  110  120  130  140
1     0.2     101  111  121  131  141
2     0.3     102  112  122  132  142
3     0.4     103  113  123  133  143
4     0.5     104  114  124  134  144
5     0.6     105  115  125  135  145
6     0.7     106  116  126  136  146
7     0.8     107  117  127  137  147
8     0.9     108  118  128  138  148
9     1.0     109  119  129  139  149
```


```python
> print(df[['x0', 'x1']])

               x0   x1
index weight          
0     0.1     100  110
1     0.2     101  111
2     0.3     102  112
3     0.4     103  113
4     0.5     104  114
5     0.6     105  115
6     0.7     106  116
7     0.8     107  117
8     0.9     108  118
9     1.0     109  119
```


```python
> print(df.x0)

index  weight
0      0.1       100
1      0.2       101
2      0.3       102
3      0.4       103
4      0.5       104
5      0.6       105
6      0.7       106
7      0.8       107
8      0.9       108
9      1.0       109
Name: x0, dtype: int64
```

```python
> print(df[2:5])

               x0   x1   x2   x3   x4
index weight                         
2     0.3     102  112  122  132  142
3     0.4     103  113  123  133  143
4     0.5     104  114  124  134  144
```

**Comment by williamjameshandley** [comment]
I strongly disagree with the first suggestion, but the second may well be truly inspired, as it would also get around a lot of the issues associated with Series and DataFrames.

The fundamental question is whether we can get `samples.weight` to neatly access the multi index correctly (Pretty sure this should be possible), in order to avoid breaking things in a backward incompatible fashion.

**Comment by williamjameshandley** [comment]
The more I think about this, the more I get a 'why didn't I think of this in the first place?' vibe, which in my book is a good sign. In the interests of full consideration though, it's worth our trying to shoot it down as much as possible before getting started.

- Is it going to make slicing an array over the index hard/ugly, if ever we wanted to do that (e.g. in the live_points function)?
- Is iteration + weight theoretically in keeping with an 'index'? 
- Will this make operations on/between arrays hard?

I think that if we were to make this change, we should consider a major version bump to 2.0.0, as it is arguably an API shift (although hopefully not if we get it right).

**Comment by williamjameshandley** [comment]
The other thing worth considering alongside the above points is whether we even need an iteration index, and whether one could just have weight on its own.

**Comment by lukashergt** [comment]
> The other thing worth considering alongside the above points is whether we even need an iteration index, and whether one could just have weight on its own.

For compatibility with MCMC chains, where the weights are not unique, I think it is better to retain an iteration index.

**Comment by lukashergt** [comment]
> The fundamental question is whether we can get `samples.weight` to neatly access the multi index correctly

Make `samples.weight` a property returning the index?

E.g. along these lines:
```python
class WeightedDataFrame(pandas.DataFrame):
    
    def __init__(self, data, columns, weight):
        index = np.arange(weight.size)
        indices = pandas.MultiIndex.from_tuples(zip(index, weight), names=['index', 'weight'])
        super(WeightedDF, self).__init__(data=data, index=indices, columns=columns)
    
    @property
    def weight(self):
        return self.index.get_level_values('weight').to_numpy()

df = WeightedDF(data, columns=params, weight=weight)
```

```python
> df.weight

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```

```python
> df.weight[0]

0.1
```

We'd need a way for subsamples to access that property, though.

**Comment by lukashergt** [comment]
> * Is it going to make slicing an array over the index hard/ugly, if ever we wanted to do that (e.g. in the live_points function)?

Not sure what you mean, as shown in my first examples `df[2:5]` is still possible without any complication. Is that what you mean?


> * Is iteration + weight theoretically in keeping with an 'index'?

In nested sampling, weights are an ordered list, so they could be almost viewed as an index of their own, right? In MCMC, weights are essentially a counter for line repetitions, which has an index quality to it too...


> * Will this make operations on/between arrays hard?

Using a `MultiIndex` definitely makes indexing a bit more complex when it comes to actually using the index (see above: `self.index.get_level_values('weight').to_numpy()`). However, it shouldn't be necessary to directly use the multi indexing that often, right?

**Comment by williamjameshandley** [comment]
>For compatibility with MCMC chains, where the weights are not unique, I think it is safer to retain an iteration index.

Agreed

>Not sure what you mean, as shown in my first examples df[2:5] is still possible without any complication. Is that what you mean?

Yes. Neat.

>Make samples.weight a property returning the index?

Yes.

>In nested sampling, weights are an ordered list, so they could be almost viewed as an index of their own, right? In MCMC, weights are essentially a counter for line repetitions, which has an index quality to it too...

I can definitely buy this reasoning (pandas has a pretty loose notion of index anyway).

>Using a MultiIndex definitely makes indexing a bit more complex when it comes to actually using the index (see above: self.index.get_level_values('weight').to_numpy()). However, it shouldn't be necessary to directly use the multi indexing that often, right?

I think this makes sense, or at least not so much a concern to not give it a go.



Who wants to have a go at doing this? I have some time this afternoon to look at it, but if you'd prefer to do it let me know soon.

**Comment by lukashergt** [comment]
> Who wants to have a go at doing this? I have some time this afternoon to look at it, but if you'd prefer to do it let me know soon.

You are much more familiar with pandas inheritance stuff, so you'll probably have an easier time. I'd need to do more reading on the whole `_constructor` business. At a quick glance, I wasn't able to figure out how to make a slice/subsample inherit a property (`weight`) from the main sample. You've already made this happen in the current version, so probably better if you have a go at it.

**Comment by williamjameshandley** [comment]
OK. The only possible remaining issue is what to do about the `_rand` attribute (used to consistently compress), which is treated similarly to the weights, but not user-accessible. This is not associated with this issue, but may be with the underlying issues in #115. I'll see how I get on.

**Comment by lukashergt** [comment]
> OK. The only possible remaining issue is what to do about the `_rand` attribute.

* Keep that as it is now? `_rand` is different from `weight` in that it's not really something that needs to be displayed (maybe even should not...?). Therefore there is no need of syncing a column with an attribute.

* Another index? Though not really something that needs displaying maybe it doesn't hurt...? Then it can be handled alongside the `weight` index.

Another thing that I've been wondering is whether `logL` is another candidate for an index. It is not a parameter like the rest in data, rather each `logL` is associate with a complete parameter set...

**Comment by williamjameshandley** [comment]
>Another thing that I've been wondering is whether logL is another candidate for an index. It is not a parameter like the rest in data, rather each logL is associate with a complete parameter set (i.e. the complete row)...

I think if we start adding too much, it will begin to get messy. I'm also not sure I agree that logL isn't of the same status as a derived parameter (it is for the purposes of computing things like the DKL).
