### ISSUE TITLE
Weight normalisation

### ISSUE THREAD

**Issue by williamjameshandley** [williamjameshandley/anesthetic#90]
Currently in anesthetic the nested sampling weights are normalised so that the maximum weight is 1. The other convention (more consistent with multinest, and possibly safer) is to normalise so that they sum to 1. I don't think this would be a breaking change for anybody, since if you were to be using the current weights directly, you would probably be normalising anyway.

What are people's views on changing this? @lukashergt @appetrosyan @Pablo-Lemos 

This is a change that could likely be implemented at the same time as fixing #83

**Comment by appetrosyan** [comment]
Can we create a new function and deprecate the old one? I would argue that the normalisation convention is an internal implementation issue, so it shouldn't be directly exposed. I would add a layer of getters and setters and change the internal representation.

**Comment by lukashergt** [comment]
Either way would work for me. 

Important to me is that subsamples/slicing/masking/etc. work as expected. That means that we shouldn't rely on a certain normalisation within the code. In places where we need the weights normalised by their sum we should use `w/w.sum()` and not just `w` which would only be normalised for the full sample.

**Comment by williamjameshandley** [comment]
Closing this for now -- going with the status quo, rather than making a change. Feel free to resurrect this issue if you feel strongly about weights being normalised to unity.
